apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-agent
  namespace: monitoring
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-agent
      operator.prometheus.io/name: kube-prometheus-stack-prometheus
