apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    fullnameOverride: kube-prometheus-stack
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      agentMode: true
      ingress:
        enabled: false
      prometheusSpec:
        replicas: 2
        replicaExternalLabelName: __replica__
        podAntiAffinity: hard
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        externalLabels:
          cluster: feather-core
        remoteWrite:
          - url: http://mimir-gateway.grafana.svc.cluster.local/api/v1/push
            sendExemplars: true
            queueConfig:
              capacity: 10000
              minShards: 4
              maxShards: 20
              maxSamplesPerSend: 5000
