apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/alloy-receiver
  - httproute.yaml
  - grpcroute.yaml
patches:
  - path: release.yaml
