apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vulpes-backend
  namespace: vulpes
spec:
  releaseName: vulpes-backend
  chart:
    spec:
      chart: ./helm/micronaut
      sourceRef:
        kind: GitRepository
        name: helmcharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
