apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform/clusters/feather-core/priorityclasses
  - ../../../platform/clusters/feather-core/spegel
  - ../../../databases/clusters/feather-core/mariadb-operator-crds
  - ../../../databases/clusters/feather-core/mongodb-operator-crds
  - ../../../networking/clusters/feather-core/envoy-crds
  - ../../../networking/clusters/feather-core/metallb/admission-policy
  - ../../../storage/clusters/feather-core/snapshot-controller
  - ../../../platform/clusters/feather-core/descheduler
  - ../../../platform/clusters/feather-core/workload-admission-policies
