apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-galera
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - mariadb.yaml
  - users
  - databases
  - grants
  - passwords
  - backup-to-ceph.yaml
  - backup-to-s3.yaml

secretGenerator:
  - name: mariadb
    envs:
      - mariadb-root.env
