apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
  namespace: mariadb-galera
spec:
  image: "mariadb:11.4"
  replicas: 3
  galera:
    enabled: true

  storage:
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      resources:
        requests:
          storage: 50Gi
      accessModes: ["ReadWriteOnce"]

  rootPasswordSecretKeyRef:
    name: mariadb
    key: password

  bootstrapFrom:
    s3:
      bucket: mariadb-galera-restore-point
      prefix: "backups/phys-2025-08-11"
      endpoint: "minio.minio.svc.cluster.local:9000"
      accessKeyIdSecretKeyRef:
        name: mariadb
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb
        key: secret-access-key
    backupContentType: Physical
    stagingStorage:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
  service:
    type: ClusterIP
  primaryService:
    type: LoadBalancer
    metadata:
      annotations:
        io.cilium/lb-ipam-ips: 10.200.32.4