apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-crds
spec:
  chartRef:
    kind: OCIRepository
    name: envoyproxy-crds
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  timeout: 5m
  values:
    crds:
      gatewayAPI:
        enabled: true
        channel: standard
      envoyGateway:
        enabled: true