apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../infrastructure/base/controllers/metallb
  - ../../../../infrastructure/base/controllers/proxmox-csi
  - ../../../../infrastructure/base/controllers/cert-manager
patches:
  - path: cert-manager/release.yaml