apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../infrastructure/base/controllers/proxmox-csi
  - ../../../../infrastructure/base/controllers/traefik
  - ../../../../infrastructure/base/controllers/cert-manager
  - ../../../../infrastructure/base/controllers/step-certificates
  - ../../../../infrastructure/base/controllers/checkmk
  - ../../../../infrastructure/base/controllers/mariadb-operator-crds
  - ../../../../infrastructure/base/controllers/mariadb-operator
patches:
  - path: cert-manager/release.yaml
  - path: step-certificates/release.yaml
  - path: traefik/release.yaml
  - path: checkmk/release.yaml