apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ccm
  - ../../../../infrastructure/base/controllers/proxmox-csi
  - ../../../../infrastructure/base/controllers/ingress-nginx
  - ../../../../infrastructure/base/controllers/cert-manager
  - ../../../../infrastructure/base/controllers/step-certificates
#  - ../../../../infrastructure/base/controllers/checkmk
  - ../../../../infrastructure/base/controllers/mariadb-operator-crds
  - ../../../../infrastructure/base/controllers/mariadb-operator
  - ../../../../infrastructure/base/controllers/crossplane
  - https://github.com/minio/operator?ref=v7.1.1
#  - backstage
#  - ../../../../infrastructure/base/controllers/cnpg-operator
patches:
  - path: cert-manager/release.yaml
  - path: step-certificates/release.yaml
  - path: ingress-nginx/release.yaml
#  - path: checkmk/release.yaml
  - path: crossplane/release.yaml
#  - path: cnpg-operator/release.yaml