apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../infrastructure/base/controllers/proxmox-csi
  - ../../../../infrastructure/base/controllers/cert-manager
  - ../../../../infrastructure/base/controllers/step-certificates
patches:
  - path: cert-manager/release.yaml
  - path: step-certificates/release.yaml