apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluemap
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - deploy.yaml
  - svc.yaml
  - ingress.yaml
