apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql-ha
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/postgresql-ha/
patches:
  - path: release.yaml

secretGenerator:
  - name: postgresql-ha-postgresql
    envs:
      - postgresql.env
