apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/harbor/
patches:
  - path: release.yaml

#secretGenerator:
#  - name: minio-password-secret
#    envs:
#      - minio.env
