apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: outline
spec:
  releaseName: outline
  chart:
    spec:
      chart: ./helm/outline
      sourceRef:
        kind: GitRepository
        name: helmcharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
