apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otis
  namespace: otis
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: otis-micronaut
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: feather-standard
  values:
    image:
      repository: harbor.onelitefeather.dev/onelitefeather/otis
      pullPolicy: IfNotPresent
      tag: "1.14.1"
    imagePullSecrets:
      - name: harbor-pull
    service:
      port: 8080
    metrics:
      enabled: true
      path: /prometheus
      serviceMonitor:
        enabled: true
    ingress:
      enabled: false
    httpRoute:
      enabled: true
      parentRefs:
        - name: eg
          namespace: envoy
          sectionName: https
      hostnames:
        - otis.apps.onelite.feather
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
    profiles: [ "prod" ]

    config:
      base: |-
        micronaut:
          application:
            name: Otis Backend
            server:
              port: 8080
            netty:
              access-logger:
                enabled: false
      profiles:
        prod: |-
          router:
            static-resources:
              swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
              swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
          endpoints:
            health:
              enabled: true
              sensitive: false
            metrics:
              enabled: true
              sensitive: true
          micrometer:
            metrics:
              enabled: true
            export:
              prometheus:
                enabled: true
          logger:
            levels:
              root: WARN
              "org.hibernate.SQL": WARN
              "org.hibernate.type.descriptor.sql": WARN
              "org.hibernate.orm.connections.pooling": WARN
              "com.zaxxer.hikari": WARN
          jpa:
            default:
              properties:
                hibernate:
                  hbm2ddl.auto: none
                  format_sql: false
                  show_sql: false
                  jdbc.lob.non_contextual_creation: true
                  connection.provider_disables_autocommit: true
                  jdbc.batch_size: 50
                  order_inserts: true
                  order_updates: true
                  jdbc.batch_versioned_data: true
          datasources:
            default:
              dialect: POSTGRES
              url: $${JDBC_URL}
              username: $${DB_USER}
              password: $${DB_PASS}
              driver-class-name: org.postgresql.Driver
              schema-generate: NONE
              maximumPoolSize: 20
              minimumIdle: 4
              autoCommit: false
              poolName: "HikariPool-Otis-Backend"
              connectionTimeout: 10000
              validationTimeout: 5000
              idleTimeout: 600000
              maxLifetime: 1700000
              keepaliveTime: 300000
              registerMbeans: true
              leakDetectionThreshold: 20000
              transactionIsolation: TRANSACTION_READ_COMMITTED
    envFrom:
      - secretRef:
          name: otis-app-db
    env:
      - name: LOG_JSON
        value: "true"
    readinessProbe:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 10
