apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: dc06-peer
  namespace: metallb-system
spec:
  myASN: 64606
  peerASN: 64504
  peerAddress: 10.200.3.1
  peerPort: 180
  nodeSelectors:
  - matchLabels:
      topology.kubernetes.io/zone: "dc06"