apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  releaseName: reposilite
  chart:
    spec:
      chart: reposilite
      sourceRef:
        kind: HelmRepository
        name: reposilite
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  # https://github.com/reposilite-playground/reposilite-helm/blob/main/charts/reposilite/values.yaml
  values: {}
