apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/loki
patches:
  - path: release.yaml

secretGenerator:
  - name: loki-s3
    envs:
      - loki-s3.sops.env
  - name: loki-ingress-auth
    files:
      - auth=loki-ingress-auth.sops.conf
