apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  valuesFrom:
    - kind: Secret
      name: loki-s3
      valuesKey: accessKeyId
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: loki-s3
      valuesKey: secretAccessKey
      targetPath: loki.storage.s3.secretAccessKey
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      limits_config:
        retention_period: 168h
      compactor:
        retention_enabled: true
        delete_request_store: s3
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
        s3:
          endpoint: https://s3.onelitefeather.net
          region: us-west-1
          s3ForcePathStyle: true
          insecure: false
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 2
          memory: 2Gi
      persistence:
        enabled: true
        size: 20Gi
        storageClass: rook-external-rbd
        accessModes:
          - ReadWriteOnce
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
    gateway:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: step-ca
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: loki-ingress-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Loki"
        hosts:
          - host: loki.apps.onelite.feather
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: loki-apps-onelite-feather-tls
            hosts:
              - loki.apps.onelite.feather
    lokiCanary:
      enabled: true
      kind: DaemonSet
      push: true
      labelname: pod
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    monitoring:
      dashboards:
        enabled: true
      rules:
        enabled: true
      serviceMonitor:
        enabled: true
