creation_rules:
  - pgp: 0231831CB40B8E587B7353CBA3AF727721205A62
    path_regex: .*.env
  - path_regex: .*.yaml
    encrypted_regex: ^(ca_password|provisioner_password|intermediate_ca_key|root_ca_key)$
    pgp: 0231831CB40B8E587B7353CBA3AF727721205A62
