apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-dc06
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: "dc06"
  bgpInstances:
    - name: "dc06-64606"
      localASN: 64606
      peers:
        - name: "opnsense-dc06"
          peerASN: 64504
          peerAddress: 10.200.3.1
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-fr01
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/zone: "fr01"
  bgpInstances:
    - name: "fr01-64606"
      localASN: 64606
      peers:
        - name: "pfsense-fr01"
          peerASN: 64501
          peerAddress: 192.168.68.5
          peerConfigRef:
            name: "cilium-peer"