apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: advertise-lb
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP