apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-peerconfig.yaml
  - 02-clusterconfig.yaml
  - 03-advertise-podcidr.yaml
  - 03-bgp-advertise-lb.yaml
  - lb-dc01.yaml
  - lb-dc06.yaml
