apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: awx-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://ansible-community.github.io/awx-operator-helm/