apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - nginx.yml
  - mariadb-operator.yml
  - cnpg.yml
  - helmcharts.yml
  - node-red.yml
  - reposilite.yml
  - smallstep.yml
  - jetstack.yml
  - bitnami.yml