apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
  ref:
    semver: "=0.4.0"