apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: bakery
  namespace: rook-ceph-fr01
spec:
  store: feather-s3
  displayName: bakery
  capabilities:
    bucket: "*"
    user: "*"
