apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: bluemap
  namespace: rook-ceph-fr01
spec:
  store: feather-s3
  displayName: bluemap
  capabilities:
    bucket: "*"
    user: "*"
