apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-fr01
resources:
  - harbor.yaml
  - loki.yaml
  - velero.yaml
  - mariadb.yaml
  - postgresql-cluster-backup.yaml
  - bluemap.yaml
  - reposilite.yaml
  - leantime.yaml
  - outline.yaml
  - plane.yaml
  - mimir.yaml
  - reposilite-public.yaml
  - bakery.yaml
  - olf.yaml
  - tempo.yaml
