apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: outline
  namespace: rook-ceph-fr01
spec:
  store: feather-s3
  displayName: outline
  capabilities:
    bucket: "*"
    user: "*"
