apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmk-monitoring
  namespace: checkmk-monitoring
spec:
  releaseName: checkmk
  chart:
    spec:
      chart: checkmk
      sourceRef:
        kind: HelmRepository
        name: checkmk-chart
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
