apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-red
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/node-red/
patches:
  - path: release.yaml

secretGenerator: []
#  - name: minio-password-secret
#    envs:
#      - minio.env
