apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  chart:
    spec:
      version: "*"
  values:
    persistence:
      enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: step-ca
        ingress.kubernetes.io/proxy-body-size: 2G
        nginx.ingress.kubernetes.io/proxy-body-size: 2G
      className: nginx
      enabled: true
      hosts:
        - host: node-red.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
      tls:
        - certificate:
            enabled: true
            issuerRef:
              kind: ClusterIssuer
              name: step-ca
          hosts:
            - node-red.apps.onelite.feather
          secretName: node-red-apps-onelite-feather-tls