apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  chart:
    spec:
      version: ">=1.3.20"
  values:
    ## Readiness and liveness probes
    probes:
      port: 8080 # The port Reposilite is running on inside the pod.
      scheme: "HTTP" # Scheme to use in GET requests.
      readiness:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 1
      liveness:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
    persistence:
      enabled: false
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    resources:
      requests:
        cpu: 600m
        memory: 256Mi
      limits:
        cpu: 2
        memory: 2Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 75
#        - type: Resource
#          resource:
#            name: memory
#            target:
#              type: Utilization
#              averageUtilization: 99
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
    env:
      - name: JAVA_OPTS
        value: "-Xmx64M -Dreposilite.s3.pathStyleAccessEnabled=true"
      - name: REPOSILITE_LOCAL_DATABASE
        valueFrom:
          secretKeyRef:
            name: reposilite-secrets
            key: DATABASE
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: step-ca
        ingress.kubernetes.io/proxy-body-size: "2G"
        nginx.ingress.kubernetes.io/proxy-body-size: "2G"
      hosts:
        - host: reposilite.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
#        - host: repo.onelitefeather.dev
#          paths:
#            - path: /
#              pathType: Prefix
      tls:
        - secretName: reposilite-apps-onelite-feather-tls
          hosts:
            - reposilite.apps.onelite.feather
