apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
spec:
  chartRef:
    kind: OCIRepository
    name: envoyproxy
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  timeout: 5m
  values: {}