apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otis
generatorOptions:
  disableNameSuffixHash: true
resources:
  - harbor-pull.secret.yaml
  - basic-auth.secret.yaml
  - ../../../../../apps/base/otis/
patches:
  - path: release.yaml

secretGenerator:
  - name: otis-app-db
    envs:
      - otis.env
