apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otis
  namespace: otis
spec:
  values:
    image:
      repository: harbor.onelitefeather.dev/otis/otis
      pullPolicy: IfNotPresent
      tag: "1.4.0"
    imagePullSecrets:
      - name: harbor-pull
    service:
      port: 8080
    profiles: [ "prod" ]

    config:
      base: |-
        micronaut:
          application:
            name: otis
      profiles:
        prod: |-
          datasources:
            default:
              url: ${JDBC_URL}
              username: ${DB_USER}
              password: ${DB_PASS}
              driver-class-name: org.postgresql.Driver
    envFrom:
      - secretRef:
          name: otis-app-db

    readinessProbe:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 10