apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otis
  namespace: otis
spec:
  values:
    image:
      repository: harbor.onelitefeather.dev/otis/otis
      pullPolicy: IfNotPresent
      tag: "1.3.3"
    imagePullSecrets:
      - name: harbor-pull