apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/loki/
patches:
  - path: release.yaml

secretGenerator:
  - name: auth-minio-secret
    envs:
      - loki.env
