apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  chart:
    spec:
      version: "*"
  valuesFrom:
    - kind: Secret
      name: auth-minio-secret
      valuesKey: GF_S3_ACCESS_KEY
      targetPath: loki.storage.s3.secretAccessKey
    - kind: Secret
      name: auth-minio-secret
      valuesKey: GF_S3_SECRET_KEY
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: auth-minio-secret
      valuesKey: GF_S3_URL
      targetPath: loki.storage.s3.s3
  values:
    commonConfig:
      replication_factor: 1
    loki:
      auth_enabled: false
      ingester:
        chunk_encoding: snappy
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 4
      structuredConfig:
        memberlist:
          cluster_label: "loki"
      schemaConfig:
        configs:
          - from: "2025-03-25"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 672h # 28 days retention

      storage:
        filesystem: null
        type: s3
        bucketNames:
          chunks: loki-chunk
          ruler: loki-ruler
          admin: loki-admin
        s3:
          # AWS endpoint URL
          endpoint: http://minio.minio.svc.cluster.local:9000
          # AWS region where the S3 bucket is located
          region: null
          # AWS signature version (e.g., v2 or v4)
          # Forces the path style for S3 (true/false)
          s3ForcePathStyle: true
          # Allows insecure (HTTP) connections (true/false)
          insecure: true
          sse_encryption: false
          # HTTP configuration settings
          http_config:
            idle_conn_timeout: 90s
            response_header_timeout: 0s
            insecure_skip_verify: true

    minio:
      enabled: false

    deploymentMode: SingleBinary

    singleBinary:
      replicas: 3
    chunksCache:
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1

    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0