apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: grafana
spec:
  values:
    minio:
      enabled: false
    kafka:
      enabled: false
    global:
      extraEnvFrom:
        - secretRef:
            name: mimir-s3
    mimir:
      structuredConfig:
        multitenancy_enabled: false
        ingest_storage:
          enabled: false
        ingester:
          push_grpc_method_enabled: true
        limits:
          accept_ha_samples: true
          ha_cluster_label: cluster
          ha_replica_label: __replica__
          compactor_blocks_retention_period: 365d
        common:
          storage:
            backend: s3
            s3:
              endpoint: s3.onelitefeather.net
              region: us-west-1
              access_key_id: ${AWS_ACCESS_KEY_ID}
              secret_access_key: ${AWS_SECRET_ACCESS_KEY}
              insecure: false
        blocks_storage:
          backend: s3
          s3:
            bucket_name: mimir-blocks
            endpoint: s3.onelitefeather.net
            region: us-west-1
            access_key_id: ${AWS_ACCESS_KEY_ID}
            secret_access_key: ${AWS_SECRET_ACCESS_KEY}
            insecure: false
          tsdb:
            dir: /data/tsdb
        alertmanager_storage:
          backend: s3
          s3:
            bucket_name: mimir-alertmanager
            endpoint: s3.onelitefeather.net
            region: us-west-1
            access_key_id: ${AWS_ACCESS_KEY_ID}
            secret_access_key: ${AWS_SECRET_ACCESS_KEY}
            insecure: false
        ruler_storage:
          backend: s3
          s3:
            bucket_name: mimir-ruler
            endpoint: s3.onelitefeather.net
            region: us-west-1
            access_key_id: ${AWS_ACCESS_KEY_ID}
            secret_access_key: ${AWS_SECRET_ACCESS_KEY}
            insecure: false
        distributor:
          ha_tracker:
            enable_ha_tracker: true
            kvstore:
              store: memberlist
    gateway:
      enabled: true
      replicas: 2
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
      ingress:
        enabled: false
      podDisruptionBudget:
        maxUnavailable: 1
    alertmanager:
      replicas: 2
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
      persistentVolume:
        enabled: true
        storageClass: ceph-rbd-fr01
        size: 10Gi
    ingester:
      replicas: 3
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 1536Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
      persistentVolume:
        enabled: true
        storageClass: ceph-rbd-fr01
        size: 20Gi
      zoneAwareReplication:
        enabled: false
    querier:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    query_frontend:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    query_scheduler:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    ruler:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    overrides_exporter:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    rollout_operator:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    distributor:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 2Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
    store_gateway:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 1Gi
      persistentVolume:
        enabled: true
        storageClass: ceph-rbd-fr01
        size: 10Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
      zoneAwareReplication:
        enabled: false
    compactor:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 1Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - fr01
      persistentVolume:
        enabled: true
        storageClass: ceph-rbd-fr01
        size: 10Gi
    metaMonitoring:
      serviceMonitor:
        enabled: true
