apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists

    logVerbosityLevel: 4

    enabledControllers:
      - cloud-node-lifecycle

    # -- Proxmox cluster config stored in secrets.
    existingConfigSecret: proxmox-ccm-config
    # -- Proxmox cluster config stored in secrets key.
    existingConfigSecretKey: config.yaml