apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../databases/clusters/feather-core/cnpg-operator
  - ../../../databases/clusters/feather-core/mariadb-operator
  - ../../../databases/clusters/feather-core/dragonfly-operator
  - ../../../databases/clusters/feather-core/mongodb-operator
