apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: outline
spec:
  values:
    image:
      repository: docker.getoutline.com/outlinewiki/outline
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.87.3"
    replicaCount: 1
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/proxy-body-size: "5G"
        nginx.ingress.kubernetes.io/proxy-body-size: "5G"
      hosts:
        - host: outline.onelitefeather.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: outline-onelitefeather-dev-tls
          hosts:
            - outline.onelitefeather.dev
    livenessProbe:
      initialDelaySeconds: 300
      httpGet:
        path: /_health
        port: 3000
    readinessProbe:
      initialDelaySeconds: 300
      httpGet:
        path: /_health
        port: 3000
    outline:
      # Generic Outline environment variables
      general:
        nodeEnv: production
        url: "https://outline.onelitefeather.dev"
        cdnUrl: ""
        forceHttps: true
        enableUpdates: true
        webConcurrency: 5
        maxImportSize: "5120000"
        utilsSecret: ""
        secretKey: ""
        sslKey: ""
        sslCert: ""
        defaultLanguage: en_US
        dropboxKey: ""
        logLevel: verbose
        existingSecret: "outline-secret"
      rateLimiter:
        enabled: false
        requests: 1000
        durationWindow: 60
      sentry:
        dsn: ""
        environment: ""
        existingSecret: ""
      notion:
        clientId: ""
        clientSecret: ""
        existingSecret: ""
      database:
        url: ""
        connectionPoolMin: 5
        connectionPoolMax: 15
        pgSslMode: disable
        existingSecret: "outline-secret"
      slackChannel:
        verificationToken: ""
        appId: ""
        messageActions: true
        existingSecret: ""
      redis:
        url: ""
        existingSecret: "outline-secret"
      auth:
        slack:
          clientId: ""
          clientSecret: ""
          existingSecret: ""
        google:
          clientId: ""
          clientSecret: ""
          existingSecret: ""
        azure:
          clientId: "4ac7a2a9-4812-4745-b90b-71f0723d706e"
          clientSecret: ""
          resourceAppId: "00000003-0000-0000-c000-000000000000"
          existingSecret: "outline-secret"
        github:
          clientId: ""
          clientSecret: ""
          appName: ""
          appId: ""
          appPrivateKey: ""
          existingSecret: ""
        discord:
          clientId: ""
          clientSecret: ""
          serverId: ""
          serverRoles: ""
          existingSecret: ""
        oidc:
          clientId: ""
          clientSecret: ""
          redirectUri: ""
          tokenUri: ""
          userInfoUri: ""
          logoutUri: ""
          usernameClaim: "preferred_username"
          scopes: "openid profile email"
          displayName: "OIDC"
          existingSecret: ""
      fileStorage:
        type: s3
        uploadMaxSize: "26214400"
        local:
          rootDir: /var/lib/outline/data
        s3:
          region: "us-west-rack2"
          uploadBucketUrl: "https://api-minio.onelitefeather.dev"
          uploadBucketName: "outline"
          forcePathStyle: true
          acl: private
          existingSecret: "outline-secret"
      smtp:
        host: ""
        port: 587
        username: ""
        password: ""
        fromEmail: ""
        replyToEmail: ""
        tlsCipher: ""
        secure: true
        existingSecret: ""
