apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: grafana
spec:
  chart:
    spec:
      version: "=1.2.0"
  values:
    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy
