apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb
spec:
  selector:
    matchLabels:
      app: metallb
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
