apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-fr01
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: rclone-creds-mariadb
    envs: [secrets/mariadb.sops.env]
  - name: rclone-creds-postgresql-cluster-backup
    envs: [secrets/postgresql-cluster-backup.sops.env]
  - name: rclone-creds-harbor
    envs: [secrets/harbor.sops.env]
  - name: rclone-creds-loki
    envs: [secrets/loki.sops.env]
  - name: rclone-creds-outline
    envs: [secrets/outline.sops.env]
  - name: rclone-creds-mimir
    envs: [secrets/mimir.sops.env]
  - name: rclone-creds-bluemap
    envs: [secrets/bluemap.sops.env]
  - name: rclone-creds-reposilite
    envs: [secrets/reposilite.sops.env]
resources:
  - jobs/feather-core-cluster-pg-backup.yaml
  - jobs/mariadb-galera-backup.yaml
  - jobs/bluemap0.yaml
  - jobs/reposilite-onelitefeather-proxy.yaml
  - jobs/reposilite-onelitefeather-releases.yaml
  - jobs/reposilite-onelitefeather-snapshots.yaml
  - jobs/harbor.yaml
  - jobs/loki-ruler.yaml
  - jobs/outline.yaml
  - jobs/mimir-alertmanager.yaml
  - jobs/mimir-blocks.yaml
  - jobs/mimir-ruler.yaml
