apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  chart:
    spec:
      version: "*"
  values:
    nexus:
      replicas: 3
      persistence:
        storageClass: "standard"
        size: 100Gi
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: cilium
          cert-manager.io/cluster-issuer: step-ca
        hosts:
          - host: nexus.apps.onelite.feather
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: nexus-apps-onelite-feather-tls
            hosts:
              - nexus.apps.onelite.feather