apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  chart:
    spec:
      version: "*"
  values:
    statefulset:
      container:
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            memory: 4Gi
            cpu: 4
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: cilium
        cert-manager.io/cluster-issuer: step-ca
      hosts:
        - host: nexus.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: nexus-apps-onelite-feather-tls
          hosts:
            - nexus.apps.onelite.feather