apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmk-monitoring
  namespace: checkmk-monitoring
spec:
  chart:
    spec:
      version: "=1.7.0"
  values:
    clusterCollector:
      service:
        type: NodePort
        nodePort: 30035

