---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: feather-s3
  namespace: rook-ceph-fr01
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 2
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.feather/workload-class
                  operator: In
                  values:
                    - storage
      tolerations:
        - key: node-role.feather/storage
          operator: Equal
          value: "true"
          effect: NoSchedule
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
