apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/base/nginx-ingress/
  - ../../../apps/base/reposilite/
  - ../../../apps/base/step-certificates/
  - step-certificates/issuers.yml
patches:
  - path: nginx/release.yaml
  - path: reposilite/release.yaml
  - path: step-certificates/release.yaml


