apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/base/nginx-ingress/
  - ../../../apps/base/reposilite/
  - ../../../apps/base/cert-manager/
  - cert-manager/issuers.yaml
patches:
  - path: nginx/release.yaml
  - path: reposilite/release.yaml
  - path: cert-manager/release.yaml


