apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-ha
  namespace: mariadb-ha
spec:
  releaseName: mariadb-ha
  chartRef:
    kind: OCIRepository
    name: mariadb-ha
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  timeout: 30m
  # Default values
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  values: {}
