apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongodb
generatorOptions:
  disableNameSuffixHash: true
resources:
  - replicaset.yaml

secretGenerator:
  - name: mongodb-user-admin
    envs:
      - users/admin.sops.env
