apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongodb
generatorOptions:
  disableNameSuffixHash: true
resources:
  - replicaset.yaml
  - backup-cronjob.yaml
  - servicemonitor.yaml

secretGenerator:
  - name: mongodb-user-admin
    envs:
      - users/admin.sops.env
  - name: mongodb-user-backup
    envs:
      - users/backup.sops.env
  - name: mongodb-user-prometheus
    envs:
      - users/prometheus.sops.env
  - name: mongodb-backup-s3
    envs:
      - backup-s3.sops.env
