apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  releaseName: redis
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  timeout: 5m
  # Default values
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  values: {}
