apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dependency-track-frontend
  namespace: dependency-track
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: dependency-track
      app.kubernetes.io/name: dependency-track-frontend
