apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
  namespace: dependency-track
spec:
  chart:
    spec:
      version: "=0.39.0"
  values:

    frontend:
      replicaCount: 3
      extraEnv:
        - name: ALPINE_OIDC_ISSUER
          valueFrom:
            secretKeyRef:
              key: oidc-issuer
              name: dependency-track-env
        - name: ALPINE_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: oidc-client-id
              name: dependency-track-env
        - name: ALPINE_OIDC_ENABLED
          value: "true"
        - name: ALPINE_OIDC_USERNAME_CLAIM
          value: "email"
        - name: ALPINE_OIDC_USER_PROVISIONING
          value: "true"
        - name: ALPINE_OIDC_TEAMS_CLAIM
          value: "groups"
        - name: ALPINE_OIDC_TEAM_SYNCHRONIZATION
          value: "true"
    common:
      secretKey:
        createSecret: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/proxy-body-size: "5G"
        nginx.ingress.kubernetes.io/proxy-body-size: "5G"
      hostname: dependency-track.onelitefeather.dev
      tls:
        - secretName: dependency-track-onelitefeather-dev-tls
          hosts:
            - dependency-track.onelitefeather.dev
    apiServer:
      persistentVolume:
        enabled: true
      extraEnv:
        - name: ALPINE_OIDC_ISSUER
          valueFrom:
            secretKeyRef:
              key: oidc-issuer
              name: dependency-track-env
        - name: ALPINE_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: oidc-client-id
              name: dependency-track-env
        - name: ALPINE_OIDC_ENABLED
          value: "true"
        - name: ALPINE_OIDC_USERNAME_CLAIM
          value: "email"
        - name: ALPINE_OIDC_USER_PROVISIONING
          value: "true"
        - name: ALPINE_OIDC_TEAMS_CLAIM
          value: "groups"
        - name: ALPINE_OIDC_TEAM_SYNCHRONIZATION
          value: "true"
        - name: "ALPINE_DATABASE_USERNAME"
          valueFrom:
            secretKeyRef:
              key: db-username
              name: dependency-track-env
        - name: "ALPINE_DATABASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: db-password
              name: dependency-track-env
        - name: ALPINE_DATABASE_DRIVER
          value: "org.postgresql.Driver"
        - name: ALPINE_DATABASE_MODE
          value: "external"
        - name: ALPINE_DATABASE_URL
          value: "jdbc:postgresql://feather-core-cluster-pg-pooler-rw.cnpg-system.svc.cluster.local:5432/dependency-track"