apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../automation/clusters/feather-core/node-red
  - ../../../automation/clusters/feather-core/n8n
  - ../../../automation/clusters/feather-core/ollama
