apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: leantime
  namespace: leantime
spec:
  releaseName: leantime
  chart:
    spec:
      chart: ./helm/leantime
      sourceRef:
        kind: GitRepository
        name: helmcharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
