apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/minio/
  - middlewares.yaml
patches:
  - path: release.yaml

secretGenerator:
  - name: minio-password-secret
    envs:
      - minio.env
