apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/pyroscope/
patches:
  - path: release.yaml

secretGenerator:
  - name: auth-pyroscope-secret
    envs:
      - pyroscope.env
