apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mn.fullname" . }}-config
  labels:
    {{- include "mn.labels" . | nindent 4 }}
data:
  application.yml: |-
{{- nindent 4 .Values.config.base }}
{{- range $p, $content := .Values.config.profiles }}
  application-{{ $p }}.yml: |-
{{- nindent 4 $content }}
{{- end }}
