{{- if and .Values.secrets.enabled .Values.secrets.files }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "micronaut.fullname" . }}-secrets
  labels:
    {{- include "micronaut.labels" . | nindent 4 }}
stringData:
{{- range $p, $content := .Values.secrets.files }}
  application-{{ $p }}.yml: |-
{{- nindent 4 $content }}
{{- end }}
{{- end }}
