apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  chart:
    spec:
      version: "*"
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: node-red.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
      tls:
        hosts:
          - node-red.apps.onelite.feather
        certificate:
         enabled: true
         issuerRef:
           kind: ClusterIssuer
           name: "step-ca"