apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  chart:
    spec:
      version: ">=1.3.20"
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: step-ca
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: node-red.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: node-red-apps-onelite-feather-tls
          hosts:
            - node-red.apps.onelite.feather