apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../databases/clusters/feather-core/postgresql
  - ../../../databases/clusters/feather-core/mariadb-galera
  - ../../../networking/clusters/feather-core/gateway
  - ../../../networking/clusters/feather-core/metallb/monitoring
  - ../../../messaging/clusters/feather-core/kafka
