apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../otis/clusters/feather-core/otis-dev
  - ../../../stelaris/clusters/feather-core/stelaris-dev
  - ../../../vulpes/clusters/feather-core/vulpes-backend-dev
  - ../../../vulpes/clusters/feather-core/vulpes-generator-dev
