apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: envoy
spec:
  install:
    remediation:
      retries: 3
  interval: 1m0s
  timeout: 5m
  values:
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true
