apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bluemap/clusters/feather-core/bluemap
  - ../../../apus/clusters/feather-core/apus
  - ../../../sturnus/clusters/feather-core/sturnus
  - ../../../otis/clusters/feather-core/otis
  - ../../../stelaris/clusters/feather-core/stelaris
  - ../../../vulpes/clusters/feather-core/vulpes-backend
  - ../../../vulpes/clusters/feather-core/vulpes-generator
