apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: feather-core-cluster-pg
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 75Gi
    storageClass: ceph-rbd-fr01
  enableSuperuserAccess: true
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: fr01
    podAntiAffinityType: preferred
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            cnpg.io/cluster: feather-core-cluster-pg
  bootstrap:
    recovery:
      source: feather-core-prod-backup
  externalClusters:
    - name: feather-core-prod-backup
      barmanObjectStore:
        destinationPath: s3://feather-core-cluster-pg-backup/backups
        endpointURL: http://rook-ceph-rgw-feather-s3.rook-ceph-fr01.svc:80
        serverName: feather-core-cluster-pg
        s3Credentials:
          accessKeyId:
            name: cnpg-backup
            key: access-key-id
          secretAccessKey:
            name: cnpg-backup
            key: secret-access-key
  managed:
    roles:
      - name: harbor
        login: true
        ensure: present
        passwordSecret:
          name: role-harbor
      - name: otis
        login: true
        ensure: present
        passwordSecret:
          name: role-otis
      - name: outline
        login: true
        ensure: present
        passwordSecret:
          name: role-outline
      - name: dependency-track
        login: true
        ensure: present
        passwordSecret:
          name: role-dependency-track
      - name: backstage
        login: true
        ensure: present
        passwordSecret:
          name: role-backstage
      - name: grafana
        login: true
        ensure: present
        passwordSecret:
          name: role-grafana
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "feather-core-cluster-pg-rw-external"
              annotations:
                metallb.io/loadBalancerIPs: 10.200.90.3
            spec:
              type: LoadBalancer
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: s3-store
