apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  releaseName: node-red
  chart:
    spec:
      chart: node-red
      sourceRef:
        kind: HelmRepository
        name: node-red
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  # https://github.com/SchwarzIT/node-red-chart/blob/main/charts/node-red/values.yaml
  values: {}
