apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: step-ca
    namespace: step-ca
spec:
    chart:
        spec:
            version: '>=1.28.2'
    values:
        resources:
            limits:
                cpu: 100m
                memory: 128Mi
            requests:
                cpu: 100m
                memory: 128Mi
        autocert:
            enabled: true
        ingress:
            annotations:
                kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
            hosts:
                - host: ca.apps.onelite.feather
                  paths:
                    - path: /
                      pathType: Prefix
            tls: []
            #  - secretName: chart-example-tls
            #    hosts:
            #      - chart-example.local
            enabled: true
            ingressClassName: nginx
        # Helm template
        inject:
            enabled: true
            # Config contains the configuration files ca.json and defaults.json
            config:
                files:
                    ca.json:
                        root: /home/step/certs/root_ca.crt
                        federateRoots: []
                        crt: /home/step/certs/intermediate_ca.crt
                        key: /home/step/secrets/intermediate_ca_key
                        address: :443
                        dnsNames:
                            - ca.apps.onelite.feather
                            - 10.200.32.1
                        logger:
                            format: json
                        db:
                            type: badgerv2
                            dataSource: /home/step/db
                        authority:
                            enableAdmin: false
                            provisioners:
                                - type: JWK
                                  name: admin@onelitefeather.net
                                  key:
                                    use: sig
                                    kty: EC
                                    kid: OiMo753Qm59HojYUS-ba3w7OdmYnsDsfClv7PR3dh_A
                                    crv: P-256
                                    alg: ES256
                                    x: QeFA1tBy7Jjw04gy0fLlukrePbhXYjhG01D44wJU5Z8
                                    "y": 5jsme3MU8W82RIh816nYFq1B0_YzTiHRVw1XVTt1DNg
                                  encryptedKey: eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoiNW9paDNrUTBLWU1zMFVIN1FfNUpwQSJ9.7MdlmojjtqgTYiDo1_7nxlkkMXsBRsiAyJPYbGeNKZ4kYw3iuVZjTA.zmxMBglHQqcJ9j0v.u8hF1_zCme3dqW_W9A8VY1n5Zp-cpkGilnAsN-9lVAqrEqtw1L1zXvihLXj81bptyuaZXuYWOANboK7HyXP8KR1XVTbsPjlxZa-tbyogVncOBvHLkjU-LQipemr4z7TTd2pa4JMpwtl8ackT8P2hmHRxhybH4QYKlEZxQO7AXulqopJvO5vZi-jUiJ51O2vLh33neWYdcMIN-qPy-wogc4PQj8KCKtTOivPTxUIlhZ8C41ZU1KYlyVr818NLZLG-X2XKs_1tqokhp51O_Of7vNVaDQThMWFR9vkS8AoNSp3ss8HB6oXE2JGUIpCHpeihF_95HosicAyqwMysVIs.Qdbv7zVc8t2DNzlG37nvHg
                                  options:
                                    x509: {}
                                    ssh: {}
                        tls:
                            cipherSuites:
                                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                            minVersion: 1.2
                            maxVersion: 1.3
                            renegotiation: false
                    defaults.json:
                        ca-url: https://ca.apps.onelite.feather
                        ca-config: /home/step/config/ca.json
                        fingerprint: 8ed13e459b5fb22df3caa5f99f4c19d9b40a4685436236e8a5609e61ed1a190e
                        root: /home/step/certs/root_ca.crt
            # Certificates contains the root and intermediate certificate and
            # optionally the SSH host and user public keys
            certificates:
                # intermediate_ca contains the text of the intermediate CA Certificate
                intermediate_ca: |
                    -----BEGIN CERTIFICATE-----
                    MIIB7TCCAZOgAwIBAgIRALh56v+dmGiC4JuVSuoMnykwCgYIKoZIzj0EAwIwQDEa
                    MBgGA1UEChMRT25lTGl0ZUZlYXRoZXIgQ0ExIjAgBgNVBAMTGU9uZUxpdGVGZWF0
                    aGVyIENBIFJvb3QgQ0EwHhcNMjUwMzE1MjAyMjE3WhcNMzUwMzEzMjAyMjE3WjBI
                    MRowGAYDVQQKExFPbmVMaXRlRmVhdGhlciBDQTEqMCgGA1UEAxMhT25lTGl0ZUZl
                    YXRoZXIgQ0EgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
                    QgAEEk/dvCXaMdLicArKIE0vk8nW7eW5hW/HhAoM13K/vG5vVqylKc8L+jE1bRxK
                    y76LGEuEzt9G++/ZW9KfQNffhKNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
                    /wQIMAYBAf8CAQAwHQYDVR0OBBYEFEdca3s2HmZUPzk2A/bgnnACPUw6MB8GA1Ud
                    IwQYMBaAFGg5g8JjAFjpHcNDV4EXvCf1j/+tMAoGCCqGSM49BAMCA0gAMEUCIQDs
                    jCehbP1Q9mzF6aSikUUJmpvrZeWbuUyHO0kUGEsEQAIgOZgCbif7WLyl66fPaly7
                    v7s0wKAgsQSbTYZnxhTrAVg=
                    -----END CERTIFICATE-----
                # root_ca contains the text of the root CA Certificate
                root_ca: |
                    -----BEGIN CERTIFICATE-----
                    MIIBwjCCAWmgAwIBAgIQYxIjeKsPaPwVGMfUH++FlDAKBggqhkjOPQQDAjBAMRow
                    GAYDVQQKExFPbmVMaXRlRmVhdGhlciBDQTEiMCAGA1UEAxMZT25lTGl0ZUZlYXRo
                    ZXIgQ0EgUm9vdCBDQTAeFw0yNTAzMTUyMDIyMTZaFw0zNTAzMTMyMDIyMTZaMEAx
                    GjAYBgNVBAoTEU9uZUxpdGVGZWF0aGVyIENBMSIwIAYDVQQDExlPbmVMaXRlRmVh
                    dGhlciBDQSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmouTyyOr
                    kBGqscprzWxpCNlijTqN9q4asUPLBJsueFv8mNjOUrZ1+gMbM869MCxKzvhFWzQh
                    wDS+7wqUtocFDqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
                    AQEwHQYDVR0OBBYEFGg5g8JjAFjpHcNDV4EXvCf1j/+tMAoGCCqGSM49BAMCA0cA
                    MEQCICmm1OatTX5epT3+pkNt/GLMt0sAwTTIdIVE2agDnor4AiAVMzFjncqWF2lD
                    2hj8FAI7W1X78F14OCgFirKd/Gg8Nw==
                    -----END CERTIFICATE-----
            # Secrets contains the root and intermediate keys and optionally the SSH
            # private keys
            secrets:
                # ca_password contains the password used to encrypt x509.intermediate_ca_key, ssh.host_ca_key and ssh.user_ca_key
                # This value must be base64 encoded.
                ca_password: ENC[AES256_GCM,data:pZ6EC+7MPRKWBsZBfrU12BqVnuXvFblvOq/JQTI3+GI=,iv:7HWqSysYJu+ZvVdeCOrUvgqIxWabp7tpiYSvUF032lQ=,tag:X4qB6Y07qFiGm522xKrdag==,type:str]
                provisioner_password: ENC[AES256_GCM,data:Ky5YoJYE87FEOVqGcRf7l2pmOykA2TP192/3ymf4ooA=,iv:Lh9MKUCkeGIdQnjNRdTZUn3j3pk/xJKpM+jAMiTix+Y=,tag:6enLAlUwEBlEPtHKoHIwMA==,type:str]
                x509:
                    # intermediate_ca_key contains the contents of your encrypted intermediate CA key
                    intermediate_ca_key: ENC[AES256_GCM,data:BVb3bQ3DnKXLiJHI6h1YQCO5mlMJlDWbf4idEH6nZp80ao+prwhAg+352HS5uvwDNw1R9hr1JYdt0tbMmh9BwYmpnm/ZYxk4okGUNUaVlN0M/4voJ6dBkunBi7g5sU2ambi/HDv7CAOs3fC1WqLq5Bhc/JuyJtSCLmQZiS/rWYrqBzO9TWIvmCM2MxC46wQ6bJghr8qVL/8uU4G6JiGLfRj3UZJvWMUCJ+3YPHQCyN9JPGKwGPGyVN/tLmUDExYbxBjlnBpIdXeQjIimvrosfDPaU7Ekr/QAiWx7CW0OeAEBfdUwS8x6IwIoSw4CIafzO7mP6jLtHGR3xCzD4/pNNB+dqJ5G66/nB4aZm5m6JG8YU6DNFdg8OXyj0OMN2Mim77G3rg/oNGZQwugKZodxF5L/ezfxH5SHidw=,iv:EoXqs7HS9e1+dwwvthRPMGh6wtSFrgOW4+MfoETDjqQ=,tag:KEtSYdHcqHCzHdUFGf4XDA==,type:str]
                    # root_ca_key contains the contents of your encrypted root CA key
                    # Note that this value can be omitted without impacting the functionality of step-certificates
                    # If supplied, this should be encrypted using a unique password that is not used for encrypting
                    # the intermediate_ca_key, ssh.host_ca_key or ssh.user_ca_key.
                    root_ca_key: ENC[AES256_GCM,data:uwMAwqM5lA+8CCnsxU1Q0I9xgU1KILRlXmyBYYdqBJVcB9mTETOXLXbhJ+6c/QrUtcWRUA0GRm9KB+1SJZV0kI4xZPun0ICEGSEFQVNZjNWDRLqGleS0J/+xDQ8YXZEQyu5IJi5L93EGg9uPhcTiJFhB+mWXkNDn8b4gqZiDyGAx8Jn7xwh+gMvV9BKkNjpR2sERVffJRmR2PyC/U0emqpsrIcEzHR4m9gU4CMRUu/hr9v417PoRqFL8BZYJ9+Fh4NafPVKu3+dIgkNuMZggaEaMciWBzQ8LV8n+gcJHVn1/J9WEjOXMSBTnwrpYzZXEGEpyNOCJKLh7ca3AXesDOY9MvzpBKdWHnEYmwPzw71slb6y01iCRQC2Li03fv3zUJnS4Ny1T7HbFT5WthS2N60Q0jR2j0T5I0oA=,iv:An+mRPYMz/sUPk7usA6e91k3EkfqYx65CvkgfyA/wJI=,tag:eBBmqn9eivGi6+MPQ5nbIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-15T20:45:13Z"
    mac: ENC[AES256_GCM,data:sM3wZuJ7jqJ6CFAxtFXdghwBHiLKK+RxGgF/h+f/PJq7X1AfSDMpGMG3Ti+eVZWbVUOzPdU05fUg+EnJTznkTF5wcnSdUD/LhtnOz+aBuYnjCDP+p7EoMLRULGxaSSnD8nAnC+hS2q3UnXIQ0EO4XVdHc1MyG2n12mw0V04JxTQ=,iv:R8f9YXI+KxH55b1A3CDBXze+bvvTAuSICFVJn4dRdsc=,tag:MhZf+d6HS1SQNSFEsds0PQ==,type:str]
    pgp:
        - created_at: "2025-03-15T20:45:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwWbRp0WX+I4AQ//UndAloHufKKzjrVfxYJTv+OujgcLSla1RSZt1IilrJG2
            CqXOlUpuSpI4veqarKDVpIS4B+OpgTRbM7niUgN9uau5MK/RRS/YB5ZBYANYb4CF
            eyP3IsfSc0GzqdwBrhjOpe0tcqiQ78uXEKn6zZdswjBP3ZCU90RACi0xLrs2b53E
            jz9QkyzF/H7g+PEYHFvaw2m/q6DCQooVAr7gMjpltafECwPG7cJZlxIWizIFNpmm
            oGQEh1mHAgT+VM0bYDt5wFaSGEDOGfJTHlqyBzz9coh34WbLW9CsEuPned5w0iM+
            8lYWtvMr8gzELU71cTDL6f7IzzeaDZXcNeRcG2liJZqMEXrQhXu1dWCW8v28iugc
            n8dycnPUNOGuo8BfXqk2KfN3bYBISO5rOLjg4lQwjS7LVQVv1A43BZDhzEKMz5NG
            DBoshJMRru99IkbPK9MA5pwQKBFMoH6u6XVjSObhrJE9cLdmn9iw/1We43ODo3Re
            FKr3imE7oO3HOvmrgbB62O8zS9yDgnu91RJHy/OJGOPBUKkj1VrIStdsAXo9UCUT
            Zt3N3DcMv2SCCF/9bPkJVE7aw8tpI3yDIMuyAV02TeBEvMejUk83D+rpO3FRpvMG
            z8yDPzqzXcn7hqt/Pv05CxZ4guxX8c54Fs9zN2Sdrh7wyE9/TNvmcE5Iij2qBQzU
            aAEJAhCUTO2iNvJnxVZGd83lMJrpgGdQ0XHH5LpYRF3rIgV16JLE58ruYIxV+O1G
            rfsErHCInytu5NoSzPuD91E6SN9nM7uT8GJ10IWVia6utpmv6MUpjXTNEIgnL7Wm
            QHEOsKPeHD7y
            =Rki0
            -----END PGP MESSAGE-----
          fp: 0231831CB40B8E587B7353CBA3AF727721205A62
    encrypted_regex: ^(ca_password|provisioner_password|intermediate_ca_key|root_ca_key)$
    version: 3.9.4
