apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: outline
  namespace: rook-ceph-fr01
spec:
  bucketName: outline
  storageClassName: ceph-bucket-fr01
  additionalConfig:
    bucketOwner: outline
