apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: reposilite-snapshots
  namespace: rook-ceph-fr01
spec:
  bucketName: reposilite-snapshots
  storageClassName: ceph-bucket-fr01
  additionalConfig:
    bucketOwner: reposilite
