apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: vikunja
  namespace: rook-ceph-fr01
spec:
  bucketName: vikunja
  storageClassName: ceph-bucket-fr01
  additionalConfig:
    bucketOwner: vikunja
