apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: cilium-bgp
spec:
  virtualRouters:
    - localASN: 64532
      exportPodCIDR: false
      serviceAdvertisements: # <-- specify the service types to advertise
        - LoadBalancerIP # <-- default
        - ClusterIP      # <-- options
        - ExternalIP     # <-- options
      neighbors:
        - peerAddress: '10.200.4.1/32'
          peerASN: 64504
          peerPort: 179
          connectRetryTimeSeconds: 120
          eBGPMultihopTTL: 1
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30