apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  timeout: 5m
  values:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts