apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-ha
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/mariadb-ha/
patches:
  - path: release.yaml

secretGenerator:
  - name: mariadb-ha-mariadb
    envs:
      - mariadb.env
