apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-controller
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/action-runner-controller
patches:
  - path: release.yaml

secretGenerator:
  - name: actions-runner-controller-secret
    envs:
      - actions-runner-controller.env
