apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-controller
spec:
  releaseName: k8s-runners
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: GITHUB_TOKEN
      targetPath: githubConfigSecret.github_token
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: GITHUB_CONFIG_URL
      targetPath: githubConfigSecret.githubConfigUrl
  values:
    controllerServiceAccount:
      namespace: actions-runner-controller
      name: actions-runner-controller-gha-rs-controller
