apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reposilite
resources:
  - ../../../../../apps/base/reposilite/
patches:
  - path: release.yaml

secretGenerator:
  - name: reposilite-secrets
    envs:
      - reposilite.env
