apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  chart:
    spec:
      version: ">=1.3.20"
  values:
    persistence:
      accessMode: ReadWriteOnce
    ingress:
      enabled: true
      className: "cilium"
      annotations:
        kubernetes.io/ingress.class: cilium
        cert-manager.io/cluster-issuer: step-ca
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: reposilite.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: reposilite-apps-onelite-feather-tls
          hosts:
            - reposilite.apps.onelite.feather