apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  chart:
    spec:
      version: ">=1.3.20"
  values:
    persistence:
      accessMode: ReadWriteOnce
      size: 25Gi
    env:
      - name: REPOSILITE_LOCAL_DATABASE
        valueFrom:
          secretKeyRef:
            name: reposilite-secrets
            key: DATABASE
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: step-ca
      hosts:
        - host: reposilite.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
        - host: repo.onelitefeather.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: reposilite-apps-onelite-feather-tls
          hosts:
            - reposilite.apps.onelite.feather