apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reposilite
  namespace: reposilite
spec:
  chart:
    spec:
      version: ">=1.3.20"
  values:
    persistence:
      enabled: false
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 95
      targetMemoryUtilizationPercentage: 95
    env:
      - name: JAVA_OPTS
        value: "-Xmx64M -Dreposilite.s3.pathStyleAccessEnabled=true"
      - name: REPOSILITE_LOCAL_DATABASE
        valueFrom:
          secretKeyRef:
            name: reposilite-secrets
            key: DATABASE
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: step-ca
        ingress.kubernetes.io/proxy-body-size: "2G"
        nginx.ingress.kubernetes.io/proxy-body-size: "2G"
      hosts:
        - host: reposilite.apps.onelite.feather
          paths:
            - path: /
              pathType: Prefix
        - host: repo.onelitefeather.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: reposilite-apps-onelite-feather-tls
          hosts:
            - reposilite.apps.onelite.feather
