apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
  namespace: dependency-track
spec:
  releaseName: dependency-track
  chart:
    spec:
      chart: dependency-track
      sourceRef:
        kind: HelmRepository
        name: dependency-track-chart
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  # https://github.com/DependencyTrack/helm-charts/blob/main/charts/dependency-track/values.yaml
  values: {}
