apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: arc-chart
  namespace: flux-system
spec:
  interval: 5m
  url: https://actions-runner-controller.github.io/actions-runner-controller