apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helmcharts
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@github.com/OneLiteFeatherNET/Kubernetes-FLUX.git
  ref:
    semver: "=>1.0.0"

