apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - nginx.yml
  - reposilite.yml
  - jetstack.yml
  - smallstep.yml
  - grafana-labs.yml
  - node-red.yml
  - bitnami.yml
  - harbor.yml
  - helmcharts.yml
  - checkmk.yml
  - arc.yml
  - mariadb-operator.yml
  - proxmox-ccm.yml
  - backstage.yml
  - cnpg.yml
  - minio-operator.yml
  - crossplane.yml