apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shlink.fullname" . }}
  labels:
    {{- include "shlink.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "shlink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shlink.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shlink.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DEFAULT_DOMAIN
              value: {{ .Values.shlink.general.defaultDomain | quote }}
            - name: IS_HTTPS_ENABLED
              value: {{ .Values.shlink.general.httpsEnabled | quote }}
            - name: GEOLITE_LICENSE_KEY
              {{- if .Values.shlink.general.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.shlink.general.secretName | quote }}
                  key: GEOLITE_LICENSE_KEY
              {{- else }}
              value: {{ .Values.shlink.general.goliteLicenseKey | quote }}
              {{- end }}
            - name: TIMEZONE
              value: {{ .Values.shlink.general.timezone | quote }}
            - name: DB_DRIVER
              value: {{ .Values.shlink.database.driver | quote }}
            - name: DB_HOST
              value: {{ .Values.shlink.database.host | quote }}
            - name: DB_NAME
              value: {{ .Values.shlink.database.name | quote }}
            - name: DB_USER
              value: {{ .Values.shlink.database.user | quote }}
            - name: DB_PASSWORD
              {{- if .Values.shlink.database.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.shlink.database.secretName | quote }}
                  key: DB_PASSWORD
              {{- else }}
              value: {{ .Values.shlink.database.password | quote }}
              {{- end }}
            - name: DB_PORT
              value: {{ .Values.shlink.database.port | quote }}
            - name: REDIS_PUB_SUB_ENABLED
              value: {{ .Values.shlink.realtime.redis.enabled | quote }}
            - name: REDIS_SERVERS
              {{- if .Values.shlink.realtime.redis.secretName }}
              valueFrom:
                  secretKeyRef:
                    name: {{ .Values.shlink.realtime.redis.secretName | quote }}
                    key: REDIS_SERVERS
              {{- else }}
              value: {{ .Values.shlink.realtime.redis.servers | quote }}
              {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
