{{- if and .Values.secrets.enabled .Values.secrets.files }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "shlink.fullname" . }}-secrets
  labels:
    {{- include "shlink.labels" . | nindent 4 }}
stringData:
{{- range $name, $content := .Values.secrets.files }}
  {{ $name }}: |-
{{- nindent 4 $content }}
{{- end }}
{{- end }}
