apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: OCIRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  values: {}
