apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: onelitefeather
  namespace: minio
spec:
  pools:
    - servers: 4
      name: entenhausen
      volumesPerServer: 1
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi