apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../base/flux-notifications
# Webhook secret flux-discord-webhook.sops.env (address=<url>) is created by the maintainer.
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: flux-discord-webhook
    envs:
      - flux-discord-webhook.sops.env
