apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/jellyfin/
  - httproute.yaml
  - ingress.yaml
patches:
  - path: release.yaml
