apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/grafana/
  - middlewares.yaml
patches:
  - path: release.yaml

secretGenerator:
  - name: auth-grafana-secret
    envs:
      - grafana.env
