apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudflare-tunnel-ingress-controller
  - step-certificates
  - cnpg-operator
  - kube-prometheus-stack
  - metallb
  - ../../../../infrastructure/base/controllers/spegel
  - ../../../../infrastructure/base/controllers/mariadb-operator-crds
  - ../../../../infrastructure/base/controllers/envoy-crds
  - ../../../../infrastructure/base/controllers/snapshot-controller
  - ../../../../infrastructure/base/controllers/descheduler
