apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-ccm
  namespace: kube-system
spec:
  releaseName: proxmox-ccm
  chartRef:
    kind: OCIRepository
    name: proxmox-ccm
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  values: {}