apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../otis/clusters/feather-core/otis
  - ../../../otis/clusters/feather-core/otis-dev
  - ../../../vulpes/clusters/feather-core/vulpes-backend
  - ../../../vulpes/clusters/feather-core/vulpes-backend-dev
  - ../../../stelaris/clusters/feather-core/stelaris
  - ../../../stelaris/clusters/feather-core/stelaris-dev
  - ../../../vulpes/clusters/feather-core/vulpes-generator
  - ../../../vulpes/clusters/feather-core/vulpes-generator-dev
  # telepresence moved to services-development
