{
 "title": "Metallb",
 "description": "Metallb dashboard https://metallb.universe.tf/  ",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pool",
    "query": {
     "query": "label_values(metallb_allocator_addresses_in_use_total,pool)"
    }
   },
   {
    "name": "l2",
    "label": "l2",
    "query": {
     "query": "label_values(metallb_layer2_gratuitous_sent,instance)"
    }
   },
   {
    "name": "metallb_client",
    "label": "metallb client",
    "query": {
     "query": "label_values(metallb_k8s_client_config_loaded_bool,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Total pool", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 1 } },
  { "title": "IPv4 pool", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 3, "y": 1 } },
  { "title": "IPv6 pool", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 6, "y": 1 } },
  {
   "title": "$pool",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "repeat": "pool",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(metallb_allocator_addresses_in_use_total{pool=~\"$pool\"}[$__rate_interval]) / last_over_time(metallb_allocator_addresses_total{pool=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
   "repeat": "pool",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(metallb_allocator_ipv4_addresses_in_use_total{pool=~\"$pool\"}[$__rate_interval]) / last_over_time(metallb_allocator_ipv4_addresses_total{pool=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$pool",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 2 },
   "repeat": "pool",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(metallb_allocator_ipv6_addresses_in_use_total{pool=~\"$pool\"}[$__rate_interval]) / last_over_time(metallb_allocator_ipv6_addresses_total{pool=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "L2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Gratuitous sent", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 10 } },
  { "title": "Requests received", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 10 } },
  { "title": "Responses sent", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 10 } },
  {
   "title": "$l2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "repeat": "l2",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(metallb_layer2_gratuitous_sent{instance=~\"$l2\"}[$__rate_interval])",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "$l2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "repeat": "l2",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(metallb_layer2_requests_received{instance=~\"$l2\"}[$__rate_interval])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "$l2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "repeat": "l2",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(metallb_layer2_responses_sent{instance=~\"$l2\"}[$__rate_interval])",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  { "title": "BGP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "BGP Session Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metallb_bgp_session_up{peer=~\".+:.+\"}",
     "legendFormat": "{{pod}} - {{peer}}"
    }
   ]
  },
  {
   "title": "BGP Announced Prefixes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metallb_bgp_announced_prefixes_total{peer=~\".+:.+\"}",
     "legendFormat": "{{pod}} - {{peer}}"
    }
   ]
  },
  {
   "title": "BGP Pending Prefixes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metallb_bgp_pending_prefixes_total{peer=~\".+:.+\"}",
     "legendFormat": "{{pod}} - {{peer}}"
    }
   ]
  },
  {
   "title": "BGP Updates Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(metallb_bgp_updates_total{peer=~\".+:.+\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{peer}}"
    }
   ]
  },
  { "title": "Client metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  { "title": "Config loaded", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 56 } },
  { "title": "Config stale", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 2, "y": 56 } },
  { "title": "Client update", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 4, "y": 56 } },
  { "title": "Client update errors", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 14, "y": 56 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 57 },
   "repeat": "metallb_client",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metallb_k8s_client_config_loaded_bool{instance=~\"$metallb_client\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 57 },
   "repeat": "metallb_client",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metallb_k8s_client_config_stale_bool{instance=~\"$metallb_client\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 57 },
   "repeat": "metallb_client",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_updates_total{instance=~\"$metallb_client\"}[$__rate_interval])",
     "legendFormat": "$metallb_client"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 57 },
   "repeat": "metallb_client",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(metallb_k8s_client_update_errors_total{instance=~\"$metallb_client\"}[$__rate_interval])",
     "legendFormat": "$metallb_client"
    }
   ]
  }
 ]
}