apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  releaseName: nexus
  chart:
    spec:
      chart: nxrm-ha
      sourceRef:
        kind: HelmRepository
        name: sonatype
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  # https://github.com/sonatype/nxrm3-ha-repository/blob/main/nxrm-ha/values.yaml
  values: {}
