http:
    port: ENC[AES256_GCM,data:hVSKCw==,iv:WdffAd3tcnsCgVs9T5M+mTYrZFnQoO+rQN0BfI37dvI=,tag:jgUb23QolSfGaMJ9gtqYOQ==,type:int]
    baseURL: ENC[AES256_GCM,data:Tw==,iv:fqeVIBX0xFhAwYABF+UMtRkTD+UnSda+4K8IAa3Tq24=,tag:An4evaOa1KyqkdWaN4puuQ==,type:str]
server:
    sources:
        - path: ENC[AES256_GCM,data:ur9quQ==,iv:GwuoobByOs8gPxIU6K0RyRVOLKb/BVojLHpFRLCgJcg=,tag:0yOdAMKOoeK19Q62z4n7hQ==,type:str]
          name: ENC[AES256_GCM,data:ssxQWAOVohMh,iv:SSA+Wp0NlWIjxmyw4fInbPpzxkpcijRn0gpJbGlwiYA=,tag:mGiEeSM5slHrhOxqtAdSgg==,type:str]
          config:
            #ENC[AES256_GCM,data:VepQ9iqfv6rME8DuZxejkIfLlseu4ENFYcXCNilFjZTDFSMS3gbmidPRctCoo8xAmbmCbb8u9WyvrBAVtqnRgczH8w==,iv:Y4EwFCReglDWl6tIfkI9KOvmzL9m/Ywq1ExKVrnTVsY=,tag:2RAneX36eZ3k5gQbgOLZjQ==,type:comment]
            defaultEnabled: ENC[AES256_GCM,data:pmX7FA==,iv:Gp9+sAyNzBq16T5DsfSdwC2rCe4OhtNqhWNAkL5TBgw=,tag:ynYZKMK+G2UnIx6My8VFbQ==,type:bool]
            defaultUserScope: ENC[AES256_GCM,data:fw==,iv:9cZE9ubglg8lnjiRXPvaoDdrgXXK8J1/iPN0i6LTSos=,tag:dsHHuQnRWXL0EOP1dB9yvw==,type:str]
            createUserDir: ENC[AES256_GCM,data:joMctR0=,iv:YHl7iF94TUudBqkSZFY4FOSNrsGI6t3wgB/QqNRkLJc=,tag:S9AQ+HIzrtxMh2iMPnZ/Sw==,type:bool]
auth:
    methods:
        #ENC[AES256_GCM,data:lRp4F5chWpt7y65jPDd1MboHNpZkjjqVTYyx+3RNEAfHz/fXYxf9feuu+jqQpPnMXSNINXZ9EInZOb4efdVdOowW/8gXAOMRy/DHlg==,iv:14pW9/Kdt7zxZvB2zds0G3AkZ1DNVN4q+TaVfirp0E4=,tag:DfvnbiuBs5Oy3LTir0osqQ==,type:comment]
        password:
            enabled: ENC[AES256_GCM,data:8JsSHA==,iv:0kYobPnaCZiO7HEL7hx1cCTQmzs1IRTM0nh7PpZLVlo=,tag:CHl6aaTJuVV469FUUhXbAw==,type:bool]
            minLength: ENC[AES256_GCM,data:sis=,iv:PIZptoOVLa8/sfnYzZQkD0wdrcpQdbxrpRuhYCSHhls=,tag:4btkFwZKqhbGQV73J8CKRw==,type:int]
            signup: ENC[AES256_GCM,data:AommLYU=,iv:xV4xCblEp04ZGQkRWjUgP2hBPmY5FCiaiMs5pDQf0ng=,tag:/ShIuk71MkJtfiWQZcjOSg==,type:bool]
        oidc:
            enabled: ENC[AES256_GCM,data:739LOw==,iv:WxNo6XZxx81IuVL5NQS+DKh+SpWFHCYXLY8L0andP24=,tag:7315vMYOiPwHRnSv/M56rA==,type:bool]
            clientId: ENC[AES256_GCM,data:EzhNjX0Nupd/elNaNXY4inCUEetH/2VfDpEB253qLE8Ijjco,iv:AaY6Op/Yw+DC/BhCV+3eHDQ0OYXcm29MTwS3Z3vGykI=,tag:BChjn4CxaxIvqnMbUe9Obg==,type:str]
            clientSecret: ENC[AES256_GCM,data:gs8UB+WFHChCL3W4ieTRvzhntaMBNBo5GNonBEfx/aPNU8QGU2YPgA==,iv:BO8ZaNR9gCy6JoCuAfBhgjrIQOHzV5AoWLRVpvn2Djs=,tag:JqKQdVQImyhgj9GXKpDxkA==,type:str]
            issuerUrl: ENC[AES256_GCM,data:X4nRf3DbpAwGDXXxoTKUeG0pow1u2O3GiWzlQ6TSEZNEu7yAqw61f90zNgEn6EQWqKHGsZ+CbUc+qN5dtyOSxjOTwDGDgWI4zGJ2,iv:oOaq2dWzCFjHXYzd/sxkEq7H5n/QuwnMNstmyEYc2lc=,tag:cGAvkHjGkkRhDweT1xIZRg==,type:str]
            scopes: ENC[AES256_GCM,data:2ocBW3F0s4w0LLC5PVVpYhRf+Iw=,iv:1hS6SasHs4w9iLz79jFNVKF2KZql8pl5hKo/xrTrd0Q=,tag:/oPE1Zk2VzowA7sbwB1mWA==,type:str]
            userIdentifier: ENC[AES256_GCM,data:yFIe8a7v9cuww/zpRI+0EkKh,iv:rOAOWjBi//QnPcZJXQ2ohOwfHCHQyh54e65jBx5HX/c=,tag:YhEaaBTpkvUN98tcI7UZwQ==,type:str]
            groupsClaim: ENC[AES256_GCM,data:kWIN78Fe,iv:2v0EttZPAjJfAg4Fao7uEJKTfe+lzmNe3AI0B4f0/wc=,tag:vJrMwEXokc56nP8SKBspdw==,type:str]
            adminGroup: ENC[AES256_GCM,data:sZ5fQgTqhOQ5bzup94WVqodKUis8hh+Lvnaj81Dsn4EqQwdU,iv:j/Zo7uryCNW9FRawUN9/IIaiDS98Bd1ZPiZr5Mg3Umw=,tag:36J8SVpA8nKDIBBegbobZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNHZLUUxYd0tHWlduTFFC
            L2VNOUxGeU5MVEZpSXZRaFRaRXhzOHBhS0ZvCmFQTmxzRGN6VnlURWh5blJpREZY
            MzdLcUdpdTVBc1J3ZktBSy84UnhzMmsKLS0tIDByR3J4UmpsOG03RzVjcDU3T1hp
            RkkxWk9PVkpUZlBCWjRhZHh6YkdmVW8KzaM+MHv1R1r3s4ziuEHu48GHm3sYxrhI
            a2Z0eY5hdM9Fkxvkgra3CIhYB4gDEn99LVEGplMUvAnS2Q1NDosRIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kfcggatwrwslka8sssdw2sy05jwntft84cw979gkvzp9wksnyy0qllsz8s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVklEOGx1OEZCU2pwY0pQ
            L3lVejc2VzhQNHZoREMwMUQ2bHhlZ2loSzBZCk1ET2VjYkRrNGNNbkErbUlDME1R
            cnFOV3RxVmZpaHpsVmd4RGd4TXc2dHcKLS0tIGRJNm42U3NWOXZCK015SUFabnVH
            Yk5sZ0dodDZwTmtXUmQ4K1VPSGFJVUUKkwm4vvqmLwJcXvIYWfu0mmxaLD7ddt/T
            ThCxL9Fk5Al4F6Y27KP1+eS7HYNR7XILRLLAtCJ8zDbP0m/OAlYJ8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10x4xtzptvjztg9jkxr4m5luw3mfyqwww499lgnnqx32h2xytu5nqkjwqaq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSDZUWndqWkRLY1B5eXpq
            M0hpYXpFRDl2MW5mbWFFMWk0QlNGbG45Unl3CnVwSVFtc240SE8ybjRoUGxhaUdY
            aEdhcVdBbnAvdEU2ZkJwOEhJS3M5bVEKLS0tIEZjbWJ0UzYyUWsyVW5tdnZlS0xE
            MGdFWVlUN3o4TUhuN1pqMS9FY2JYdlEKf/gRPrj8Af1O8x5UbNst/191To1TcBue
            WnnU6n+1miZP3P0dPqD2GE3UiLd4Z6m7HZ5KUQOs08yiLwFM1kmHMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrus5c38flq6yg6l56d0cecgzap0fhdew64n7ygz7lngjwpzws4qcnge3x
    lastmodified: "2026-09-08T17:13:47Z"
    mac: ENC[AES256_GCM,data:0DBAY03JpJlNvN2OyAO3tRN3ikBss5/CCIinTtAw2AQbMf0221Lli8WMD0eZmFWs2un4R2g9Ut6bSx+IA1TNQkdqkVA46Lnk76pYL9LCl6RlyMzHLbo64IazCe4QtVCn6SpRb9O5U4W4yjjaceUHie9N3hEPZWOjrEV1udi6WVI=,iv:ORjJi5RwxqA737eWHoX8d1L/FsTvDJgtmrM3UVoWPaY=,tag:LHXax0fHNzOIkJ7+CnRDgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
