#ENC[AES256_GCM,data:Qy++DhpRUJyZn7xsdpRAYo7NCiYnanttd3uhWxN7nlPHFWkDLoo0971TT4XKGZ6S5SukqxfjKWJz4Pa5d6Dn81J2CfM1TDid,iv:9ObkKEVxHLqWJNanxQxFLGJdxf7hAUdk52nGrk5lTSQ=,tag:lHAzqK7JuCjdXvAOBynmjQ==,type:comment]
#ENC[AES256_GCM,data:/QdOHpoQRlBkLFvze/sVwgOLEUCeEW6E8xuJLl7W8Ll+vLde84C4xu86zRsvs74joV/0gyaregxhyTknIg==,iv:Ci78ROu6O/0RixsnovPCHF0djn5N3pegODHgqqv5Xe4=,tag:rEMT5t+LH9m3fN9xLQfB0w==,type:comment]
server:
    port: ENC[AES256_GCM,data:cUXm8w==,iv:bR1pgUNgW3f8KWjItDQrDc/GzduagYVyjco4g9Aw1qk=,tag:X0lZqfYM1zmAW8NBkEZRMA==,type:int]
    baseURL: ENC[AES256_GCM,data:cQ==,iv:XoWnfmcbG64VUBfp0ycz0/meMTTykWrDskarkJPC0p0=,tag:Ch/uNB3h9X5TkgBMjAHxGg==,type:str]
    sources:
        - path: ENC[AES256_GCM,data:dmI0EA==,iv:JW1MvEyBH9e7A8d2M49SYQoqnaQFxAUiE1T0trB2+es=,tag:PpDsGEhzngV7pzyvEX11vA==,type:str]
          name: ENC[AES256_GCM,data:1ZhS29+v6SmA,iv:gkEmCytL0W/7L+U85+Iife1qhIzdSiEN1mMrJyHQFO4=,tag:QaJMEPBtHqwRu+x9+PIojQ==,type:str]
          config:
            #ENC[AES256_GCM,data:1U27YrytV5PJO2VEFMQJQMC5ARzhj2d9isZnw5GeuAZGns5dDCmTvmuFIyhDBM6+gVcTjU3gws3kOXh+ix473eourg==,iv:3/D2e48dCjsq86BbAPCjFIo9lRQflcDBTVUYGoXlySA=,tag:pumM3N4lM9E/8LGGYHKmnw==,type:comment]
            defaultEnabled: ENC[AES256_GCM,data:vPvK4g==,iv:iZHjT9CsbgKBGwK249cv1T/jTJ9HZKKAIrmiRYWf4bw=,tag:M1xOMbaLOSFRUA524BWS/A==,type:bool]
            defaultUserScope: ENC[AES256_GCM,data:bg==,iv:OQY6pihr42EHJyYqbZRCEzB9VX7gUweIpWugHvruSTM=,tag:QeEaDkncX5+alY89cFfwqg==,type:str]
            createUserDir: ENC[AES256_GCM,data:uO75JwQ=,iv:do4dnk6WzILPIx9hRulHKG7MHsMQ/Drwuak8UgBA3AM=,tag:GZFB45PNQB9t/TH5dTFh8g==,type:bool]
auth:
    methods:
        #ENC[AES256_GCM,data:MghzjpM9EowPIgXmGL/uTg5S1tGt9ShEE3scSC9nBrZPjuwoItYK8DutLOE/Y9Sy/o/QNwHVhBBx1kYZUAtg14o=,iv:ZGrfXrF2oya15bn63/low7cXNDtEIVyx71eTQ9qhjtI=,tag:SfCOB548GU+jOQs4XDYJaQ==,type:comment]
        password:
            enabled: ENC[AES256_GCM,data:iIiz8w==,iv:mWNnSAYoX2DWXrBxodTa1CiSxYEX0nAEPy0fZKEUm2Y=,tag:FsaPq8oK1hb8C8hWH9CFUQ==,type:bool]
            minLength: ENC[AES256_GCM,data:7sA=,iv:69UkD5PBTK7Xk9W+h4duHckAfWjeOASm1Iy3rDQ3hDU=,tag:VGXu0SjWROLDdEMYtUmJKw==,type:int]
            signup: ENC[AES256_GCM,data:z6zCLU4=,iv:sZZuraL4iBpatVJ7A7n7vv6zciNP3Fuh6CK8ZW1gzsM=,tag:6kb5sfTHwbKTk37omF3YSg==,type:bool]
        oidc:
            enabled: ENC[AES256_GCM,data:mnNJaw==,iv:c6ZCSci5oMQRGvwLt9TgMKMchOqd2Wm0UeZmIinf774=,tag:Almd5gf45P4K9f/gOmY96Q==,type:bool]
            clientId: ENC[AES256_GCM,data:t7G632ZwJ4qiwGQCTWnv8w6ZvOIyTIEXTXss5hzfCV5+RuZr,iv:KsRs8X9au6iBhwFJhLpEMiX46JjaSBqLqigw2oPRC44=,tag:ncqorPbfStSeNrpEUt371w==,type:str]
            clientSecret: ENC[AES256_GCM,data:m09cCJcJcb8P25qj4a9mFKAwRK6Y5CQWHE3N9kMkntNRfWq/xMr8sw==,iv:OE+ob67g7VuR6jx1hAAfde3tXLdsbxlrIfRqyptHQ3A=,tag:KMkxdypKeQDRNL6Nqw+H/g==,type:str]
            issuerUrl: ENC[AES256_GCM,data:s7qPAeeSdLAQ6mDdEIqW5U0gqXBwDXLO22sgs0/P/lzlmu9XNSbhDvijYmjdKIm7h3WymACZ/nANJ+6f84ssznmdLTuuuc/CSTj7,iv:RnNpFkVzCrCWgCBcymE25VYi9s0MtZsNMQtaZy1Dpv8=,tag:RqPNLk7uzMzh/+KSmMXulA==,type:str]
            scopes: ENC[AES256_GCM,data:V1l9Nx1X/vDko/UXY8BIiUReIao=,iv:9jKqzZPSeDXebkvt+WBi5v6Bp/5T+aHZMZ8H0SSg9ek=,tag:q6oJgL6PIUNbKrBIE6dzJg==,type:str]
            userIdentifier: ENC[AES256_GCM,data:pbT8BosHTEouesdHKDjZAYW0,iv:VDLqjILGC4uYepOqpBsQ0/PxWn9NPgsNw/RuNNoK0U4=,tag:9xCuRgRyz6AJV1XclSPoDA==,type:str]
            groupsClaim: ENC[AES256_GCM,data:tIYHRhgc,iv:FxrsAukeqwzBlkSHwFACWaBVDiqj/0wc08lm/GPV/ds=,tag:jpQ6peCTmdFap+8SRVPCRw==,type:str]
            #ENC[AES256_GCM,data:k/l4oKjEPk0oirOL44jZYawiHpalgzS+QD3spoP1RCrPYUG93yXXfssrMVe72NXHKe+azrBm2FGoYu4asIeQ,iv:BxH0kTXhSoZt5jixl3RF3/bc2c+7JxoRXDUtOZ1XkXA=,tag:kfafNZ8RF77NKOBlw0yTzA==,type:comment]
            #ENC[AES256_GCM,data:AZLB6uvcSRezSWro0IOAHxpqbC+3jwO6kRCJgRailkn7aZ1UkYUjeW1Bs7240FKA,iv:C4vTovtr4JNgczfEsMOlIhicXCz0rIKmXd9FOW7xtg4=,tag:CO6AqEqj9weCpviQVKkrDQ==,type:comment]
            adminGroup: ENC[AES256_GCM,data:2V68g1lbbcmRSbOfhatw+2xeemtKdUITlLIMP+UFV06gkDc5,iv:Htv7xhy1ydqggKdhTawtB6a+OZu385+oDo0Pbw2xj8A=,tag:Sg5GjnnP8o1WnDAhIFyTsw==,type:str]
userDefaults:
    account:
        #ENC[AES256_GCM,data:V0HD/cNFc43Lk+VigsrysbT6pOj1BSVDNN58E+x1+nwlOPTYR3zzAdoFwl4gDA/9FXWF/rzoJbbC+Zd+bSbja5OLY2G24Ik=,iv:R/DJNKF4N/kvHkJiNVxfXX2BfwKd8qM0DSYWV+2UFHA=,tag:KHhd61+8RYpqRn48oAAaiQ==,type:comment]
        permissions:
            download: ENC[AES256_GCM,data:dxf/fQ==,iv:5y1iIrV9X6RMBqBGaExMW9jOMVWkbTwP9qET211EYIc=,tag:yvrykzIHaxSZnslE8CJIog==,type:bool]
            create: ENC[AES256_GCM,data:WTp9Hw==,iv:acTbdpQf8zWisKGPN0rMmhB8BJ/oxbvtl0RfR9/fPfQ=,tag:XieixaLHNOCN+wg5hb+isA==,type:bool]
            modify: ENC[AES256_GCM,data:3V6MDw==,iv:rgzqlbXutKxF5xSzpvwWsrel2/dKr+Wo+6WLRuSU/Oc=,tag:voDLXE2BpyYDadeTNymGGQ==,type:bool]
            delete: ENC[AES256_GCM,data:rkhe1g==,iv:AKWiXxicTikpidAjwdKOqSb/16lC0cRw6aPFhgTGoes=,tag:d6uyICxodhi/ADkTZMa5Ng==,type:bool]
            share: ENC[AES256_GCM,data:K3S1bgU=,iv:M1bnA2vlzccgtgIwGD/izvkMpoSE0H8qg/xv1vjnv8k=,tag:UZ0WtYZ20U8af6f2s+ad8w==,type:bool]
            api: ENC[AES256_GCM,data:44ERPLM=,iv:SiaPXOIpyqb5eYFoRQEU2s7cJSJcJU6z7kQOxPOLg8w=,tag:wyRbTar4HeNm26lg4RJBBA==,type:bool]
            admin: ENC[AES256_GCM,data:Ng0OvUE=,iv:jfghvDNFmjYvDD3YvMYSYolqzc30p1bEuxDv7D74OCA=,tag:opFTnpb3B/zYr5Mdg8ViFg==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicko4ajB0Nkh3Y3paeEl2
            TUFBWTlQUFY5OUNZNEQxaFI1bkFKUllHa1VvCjl1Qm83Q3hBSEF0WTN1RmNjOGg5
            eG8wUXpKWitickwvT1RrQWw1Q0VhMHMKLS0tIGwxbWtEZzNZSjltNTJLYnFQeStx
            U1FkRmxhMHcvRy9WYzNpSEtJYXkzU1kK0qdkDcwqiN5Amyp9xHfJ/naPzvLUZSZd
            SQ6JUuF5qzYpw9PSp/27gemg2oWl7RYZMc1z5OuHy48GWC+75Wn5fA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kfcggatwrwslka8sssdw2sy05jwntft84cw979gkvzp9wksnyy0qllsz8s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMVVXUkdvNUtUcmNoeVA0
            dUFyVGwxa05WMHFLSUo5YjJSYytjNWtSYVhzCmQ2ZXNzZnUzZEZwbE9kT0RIWUNz
            OWw1SWlSTEhDb0xNNzBhaDdtakVaSW8KLS0tIFF4R0dUMEhycFVTVU5vODA2Tjc4
            OGN2L053SDlHVSszSWdMQm9mVE9NbmcKi9Z+fOwsOGiOHDmCxdbf1J9gdDA5Bgpm
            giKEXAVcxwCMqk6zKL1aLccRRyPSxJzaClJY4CtMmR8FY7sr1piHGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10x4xtzptvjztg9jkxr4m5luw3mfyqwww499lgnnqx32h2xytu5nqkjwqaq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWnNTZ3R5d0ZzTHhPajVK
            WWttcWwxbU1RY2VNL001RlhOWUN4eDllZUZBCkg0U0VPTC81c1JKVGFjb2JsVU9w
            R3NXbWw0c1U2bkFVNkI4VHROZG1ZZWcKLS0tIGdCVGR2N21lQzJMNHhFNHcraWow
            YmRGd3NpTWtpd2xWQ2VyU3NiVURBMHcKUH9n3M4vIFXD/RVYGMmC98ndswbhxUiQ
            NA8+rio9HE426R7uEsBVSjw9f7N6K/QxPbcCh8T88NbubVUmvf9djg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rrus5c38flq6yg6l56d0cecgzap0fhdew64n7ygz7lngjwpzws4qcnge3x
    lastmodified: "2026-09-08T17:32:02Z"
    mac: ENC[AES256_GCM,data:XO6XEts824p5p4ZihTAd7nlryi3gfGWxc/pzczSTv/DJZ4yITix1tyGiX6Ld83m9mHRxO/02sTpLLVgQ/Y1JHSAh/bKg2qOX0x5/4QIlgkoK82C1b0UBeDNH7ks18kn1NJVvnxUvorjIblJC9z6c5n4H58KOvssTa1xbisxgGHE=,iv:UldZEHAitclBAhmZe7X3Zl2aIh9QKB3dVrS+mvVg+Ss=,tag:Pc7gbe5G6rU+csdAfCxllg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
