apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
spec:
  releaseName: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator-crds
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
