apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stepclusterissuer.yaml
  - internal-certificates.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: step-issuer-provisioner-password
    envs:
      - step-issuer.sops.env