apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # StepClusterIssuer is cluster-scoped; Certificates are in envoy ns
  - stepclusterissuer.yaml
  - internal-certificates.yaml
