apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: local
  namespace: metallb-system
spec:
  ipAddressPools:
  - lb-dc06
  # Per family. Both are host routes, no aggregation on either side.
  aggregationLength: 32
  aggregationLengthV6: 128
  localPref: 100
  communities: []
