apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      version: ">=1.12.0"
  values:
    controller:
      ingressClassResource:
        default: true
      service:
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: 10.200.32.1
      admissionWebhooks:
        timeoutSeconds: 30
      allowSnippetAnnotations: true
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 800m
          memory: 1Gi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 85


