apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      version: ">=4.12.0"
  values:
    controller:
      kind: DaemonSet
      allowSnippetAnnotations: true
      resources:
        limits:
          cpu: 250m
          memory: 180Mi
      service:
        externalIPs:
          - 10.200.32.1