apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../observability/clusters/feather-core/loki
  - ../../../observability/clusters/feather-core/mimir
  - ../../../observability/clusters/feather-core/opencost
  - ../../../observability/clusters/feather-core/tempo
