apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pushgateway
  namespace: pushgateway
spec:
  releaseName: pushgateway
  chartRef:
    kind: OCIRepository
    name: prometheus-pushgateway
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
