apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: mariadb
  namespace: rook-ceph-fr01
spec:
  store: feather-s3
  displayName: mariadb
  capabilities:
    bucket: "*"
    user: "*"
