apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: entenhausen-cluster-pg
  namespace: cnpg-system
spec:
  instances: 5
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 50Gi
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  bootstrap:
    pg_basebackup:
      source: bitnami-src
  replica:
    enabled: true
    source: bitnami-src
  externalClusters:
    - name: bitnami-src
      connectionParameters:
        host: postgresql-ha-pgpool.postgresql-ha.svc.cluster.local
        port: "5432"
        user: postgres
        dbname: postgres
        sslmode: disable
      password:
        name: bitnami-superuser
        key: password
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
spec:
  configuration:
    destinationPath: s3://entenhausen-cluster-pg-backup/backups
    # MariaDB uses endpoint without scheme; CNPG expects full URL
    endpointURL: http://minio.minio.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: cnpg-backup
        key: access-key-id
      secretAccessKey:
        name: cnpg-backup
        key: secret-access-key
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-to-minio
  namespace: cnpg-system
spec:
  cluster:
    name: entenhausen-cluster-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io