apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/cnpg-operator/
patches:
  - path: release.yaml