apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-system
  namespace: cnpg-system
spec:
  chart:
    spec:
      version: "=0.26.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster
  namespace: cnpg-system
spec:
  chart:
    spec:
      version: "=0.3.1"