apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m0s
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: ">=26.0.0"
  values:
    deployment:
      kind: DaemonSet
    service:
      annotations:
        io.cilium/lb-ipam-ips: "10.200.32.1"
      type: LoadBalancer
      externalTrafficPolicy: Local
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true
    metrics:
      prometheus:
        enabled: true
    ports:
      websecure:
        http3:
          enabled: true
    udp:
      enabled: true
      annotations:
        io.cilium/lb-ipam-ips: "10.200.32.1"
      ports:
        - name: websecure
          port: 443
          targetPort: 443
