apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: step-ca
    namespace: step-ca
spec:
    chart:
        spec:
            version: '>=1.28.2'
    values:
        resources:
            limits:
                cpu: 100m
                memory: 128Mi
            requests:
                cpu: 100m
                memory: 128Mi
        autocert:
            enabled: true
        service:
            targetPort: 9000
            type: LoadBalancer
            annotations:
                io.cilium/lb-ipam-ips: 10.200.32.2
        # Helm template
        inject:
            enabled: true
            # Config contains the configuration files ca.json and defaults.json
            config:
                files:
                    ca.json:
                        root: /home/step/certs/root_ca.crt
                        federateRoots: []
                        crt: /home/step/certs/intermediate_ca.crt
                        key: /home/step/secrets/intermediate_ca_key
                        address: :9000
                        dnsNames:
                            - ca.onelite.feather
                            - step-ca-step-certificates.step-ca.svc.cluster.local
                        logger:
                            format: json
                        db:
                            type: badgerv2
                            dataSource: /home/step/db
                        authority:
                            claims:
                                minTLSCertDuration: 5m
                                maxTLSCertDuration: 131400h
                                defaultTLSCertDuration: 17520h
                                disableRenewal: false
                                minHostSSHCertDuration: 5m
                                maxHostSSHCertDuration: 1680h
                                defaultHostSSHCertDuration: 720h
                                minUserSSHCertDuration: 5m
                                maxUserSSHCertDuration: 24h
                                defaultUserSSHCertDuration: 24h
                                enableAdmin: false
                            provisioners:
                                - type: JWK
                                  name: admin@onelitefeather.net
                                  key:
                                    use: sig
                                    kty: EC
                                    kid: OiMo753Qm59HojYUS-ba3w7OdmYnsDsfClv7PR3dh_A
                                    crv: P-256
                                    alg: ES256
                                    x: QeFA1tBy7Jjw04gy0fLlukrePbhXYjhG01D44wJU5Z8
                                    "y": 5jsme3MU8W82RIh816nYFq1B0_YzTiHRVw1XVTt1DNg
                                  encryptedKey: eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoiNW9paDNrUTBLWU1zMFVIN1FfNUpwQSJ9.7MdlmojjtqgTYiDo1_7nxlkkMXsBRsiAyJPYbGeNKZ4kYw3iuVZjTA.zmxMBglHQqcJ9j0v.u8hF1_zCme3dqW_W9A8VY1n5Zp-cpkGilnAsN-9lVAqrEqtw1L1zXvihLXj81bptyuaZXuYWOANboK7HyXP8KR1XVTbsPjlxZa-tbyogVncOBvHLkjU-LQipemr4z7TTd2pa4JMpwtl8ackT8P2hmHRxhybH4QYKlEZxQO7AXulqopJvO5vZi-jUiJ51O2vLh33neWYdcMIN-qPy-wogc4PQj8KCKtTOivPTxUIlhZ8C41ZU1KYlyVr818NLZLG-X2XKs_1tqokhp51O_Of7vNVaDQThMWFR9vkS8AoNSp3ss8HB6oXE2JGUIpCHpeihF_95HosicAyqwMysVIs.Qdbv7zVc8t2DNzlG37nvHg
                                  options:
                                    x509: {}
                                    ssh: {}
                                - type: ACME
                                  name: acme
                                  forceCN: true
                                  claims: {}
                        tls:
                            cipherSuites:
                                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                            minVersion: 1.2
                            maxVersion: 1.3
                            renegotiation: false
                    defaults.json:
                        ca-url: https://ca.apps.onelite.feather
                        ca-config: /home/step/config/ca.json
                        fingerprint: 8ed13e459b5fb22df3caa5f99f4c19d9b40a4685436236e8a5609e61ed1a190e
                        root: /home/step/certs/root_ca.crt
            # Certificates contains the root and intermediate certificate and
            # optionally the SSH host and user public keys
            certificates:
                # intermediate_ca contains the text of the intermediate CA Certificate
                intermediate_ca: |
                    -----BEGIN CERTIFICATE-----
                    MIIB7TCCAZOgAwIBAgIRALh56v+dmGiC4JuVSuoMnykwCgYIKoZIzj0EAwIwQDEa
                    MBgGA1UEChMRT25lTGl0ZUZlYXRoZXIgQ0ExIjAgBgNVBAMTGU9uZUxpdGVGZWF0
                    aGVyIENBIFJvb3QgQ0EwHhcNMjUwMzE1MjAyMjE3WhcNMzUwMzEzMjAyMjE3WjBI
                    MRowGAYDVQQKExFPbmVMaXRlRmVhdGhlciBDQTEqMCgGA1UEAxMhT25lTGl0ZUZl
                    YXRoZXIgQ0EgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
                    QgAEEk/dvCXaMdLicArKIE0vk8nW7eW5hW/HhAoM13K/vG5vVqylKc8L+jE1bRxK
                    y76LGEuEzt9G++/ZW9KfQNffhKNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
                    /wQIMAYBAf8CAQAwHQYDVR0OBBYEFEdca3s2HmZUPzk2A/bgnnACPUw6MB8GA1Ud
                    IwQYMBaAFGg5g8JjAFjpHcNDV4EXvCf1j/+tMAoGCCqGSM49BAMCA0gAMEUCIQDs
                    jCehbP1Q9mzF6aSikUUJmpvrZeWbuUyHO0kUGEsEQAIgOZgCbif7WLyl66fPaly7
                    v7s0wKAgsQSbTYZnxhTrAVg=
                    -----END CERTIFICATE-----
                # root_ca contains the text of the root CA Certificate
                root_ca: |
                    -----BEGIN CERTIFICATE-----
                    MIIBwjCCAWmgAwIBAgIQYxIjeKsPaPwVGMfUH++FlDAKBggqhkjOPQQDAjBAMRow
                    GAYDVQQKExFPbmVMaXRlRmVhdGhlciBDQTEiMCAGA1UEAxMZT25lTGl0ZUZlYXRo
                    ZXIgQ0EgUm9vdCBDQTAeFw0yNTAzMTUyMDIyMTZaFw0zNTAzMTMyMDIyMTZaMEAx
                    GjAYBgNVBAoTEU9uZUxpdGVGZWF0aGVyIENBMSIwIAYDVQQDExlPbmVMaXRlRmVh
                    dGhlciBDQSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmouTyyOr
                    kBGqscprzWxpCNlijTqN9q4asUPLBJsueFv8mNjOUrZ1+gMbM869MCxKzvhFWzQh
                    wDS+7wqUtocFDqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
                    AQEwHQYDVR0OBBYEFGg5g8JjAFjpHcNDV4EXvCf1j/+tMAoGCCqGSM49BAMCA0cA
                    MEQCICmm1OatTX5epT3+pkNt/GLMt0sAwTTIdIVE2agDnor4AiAVMzFjncqWF2lD
                    2hj8FAI7W1X78F14OCgFirKd/Gg8Nw==
                    -----END CERTIFICATE-----
            # Secrets contains the root and intermediate keys and optionally the SSH
            # private keys
            secrets:
                # ca_password contains the password used to encrypt x509.intermediate_ca_key, ssh.host_ca_key and ssh.user_ca_key
                # This value must be base64 encoded.
                ca_password: ENC[AES256_GCM,data:+pZk+rvwO6FhV3qMMDiE0X65WGzV8LHkkiGzKyIw37kFVnzyc7RwJewiTVQ=,iv:BdV/hlBB5IEeVzvVY6dAmGXsiwqU8eVTx0biu9+rZ+k=,tag:8WMzfH1oQfzNKI/z4ScgSw==,type:str]
                provisioner_password: ENC[AES256_GCM,data:8127iu/mVcNlNrsea9zg86aMsIEcGEVa/Eq40zfw3WmcTwZa0CxLrpB4w/E=,iv:CewYf3ZVsa9Cz4d83D2Y7a0JOvpxo34LH1rxwDJkg8k=,tag:vBYNOxTNVC2QVrL9RCUJgg==,type:str]
                x509:
                    # intermediate_ca_key contains the contents of your encrypted intermediate CA key
                    intermediate_ca_key: ENC[AES256_GCM,data:kXra4gHD/+rfAmH9/ZSXxI4gFpxT00dJgh7kqB8DjeSwUHjBdPjTpr5NarLYtPo5ii8PBPs6hgEDXp+ZUKGDDWFY/WxGjFLlGvSsVqVtYUr3yLeuttqjKpy/uh8ujuiG5tBgb8lfSMBetOzN83B4hGTGFsZqAfptm0Akv05udcHGXXjeX2N6271Zrf561lERp6LfveaalXVaOiox+w4s/H7FUNn4Vg+iVOuwoitmNpgXrzYY2iZ+ISDNw0+0rL++XIHqwOKjRc7BB+Y8icCYD1YS7OG5J41TOq+UvQy3Kqmsu5qX5FeP1QzfyEIPLa6pfCstcEegUrs8+FsDg2rt2es9/PB1oBPDxcuacjjwn1o0/6xw7GYdr77z+V2hC7scvGRS2P0PPvxiABCJslK4fdHAkoE/1uaVblE=,iv:lR0ibrvXTYcNT6q13rVhptBUCkfUzQzDTdlQ9D0hHNw=,tag:gW2K6I2isrLV658teCkVZA==,type:str]
                    # root_ca_key contains the contents of your encrypted root CA key
                    # Note that this value can be omitted without impacting the functionality of step-certificates
                    # If supplied, this should be encrypted using a unique password that is not used for encrypting
                    # the intermediate_ca_key, ssh.host_ca_key or ssh.user_ca_key.
                    root_ca_key: ENC[AES256_GCM,data:02AYM3hH9Sttw7q6nfnAiF3O604xnNv/PkgMkgf6JSh8CQWUlaNj6wAqsX+U1Z/yaVRxV8lZNoDgRwwd6fOiK7kM9Vhllu5mNgRzzrBtE32jEkiUrOlc9/g6sNrtH/t1qXasCmjmaF+S4N/qXoXnJojIawrF6ldF5Gjn4l/fegltp9falMI3VzE4sVtunIr5w68MDZdu1vmYZz057I2m8hAA6IuzjY4VwuBzOmGQ0e29E1CJUtTWgn4XNb4zRtSSrwszulTRa/wJVuY1ARtPPTyrYnlnjEe/eHyb9u/7O2bIHSJZtAjh5O9ngNLconDKIuvMTjOcFWms3NM6TR6l+eLvjRuiBw2ghShK34MEbAsuvNVoao4y4vLGl265zYCdJdcoaHbIrQMVo73hdIjDBAyQSWaVvdALj9c=,iv:m7+8jeGH6Li3XNXf2xdRQv14TyQ2QYMhkfl5XTL41U0=,tag:D1JG3TINtY/Gj1HXzNg0og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-16T17:44:25Z"
    mac: ENC[AES256_GCM,data:8dfEjR8iZIrPKBcZ/nq3K8lmukheu3lFdssm4FAmoUAHMW/WWFGar9uFYWTZVrQhB2i9bt9uNARatq9jU2h7VLyHVwBqXzLcsCnG/6u1DF8USUkjCEudKa10u0f4Ur215QLyk62oMzLKhFOzIBCtgHKeDV+IDBpT0ga4yQ5+WPk=,iv:ZsoagduEk7MwtFaUiOHIv4DnPXhA1oe3DOA2uko+o98=,tag:JgZ9SvYuxEUOmEjSIjJWoA==,type:str]
    pgp:
        - created_at: "2025-03-16T17:44:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwWbRp0WX+I4AQ/+LGZH4yODZubvhgtvIkoWMY0yv1ndkpd5aTCQNBewK28i
            y+q9hWjLrhfFZ/LdovjSOc5yhAJGNDV22rf5TY8DKG3wgzWxSmUTQy4n2ud7z1cq
            cC+XWn3L3SYN1IfgVJochq11uW/TwQc4reX0/vBNmU/VVgNG2ZxVaRc/KhMsHykN
            Oaf0uT5urJR2joWhrpRimkGBUJ8ShzoNdjUNQj9nunNkdpUO2rlEBI93y+WDLc7a
            cp6Oe0Po4KkvRnVKPCeWcep4NF/RkeR/jlwuvo2R2Q4IRjFzr1DPY7zaCsjNsHUN
            RkB9cXHIAPiZE0GsPzWHANa5IqpNy25TOpqiN/EYE0TXA+qBxapZMkd8SnYaOjKO
            CcMk18igI3eDsAbAI6GP6NKBl6Oquqw1L+GwjKPxgo130C4/jal0vN8uAkwDQNMl
            tZjXclczEw6hRSZBK2H4RJjThXAvAHU5pfJfNzx6TLzXFQaOIwU7Aqfd6ThdGY9C
            fSl8YCxrf08BO6ECJw1PV0XVez+jZgtzqvkEfkenR+hJTuO7mtEEFqTG0WhXvXEo
            qVtYoRh3Lh6A4Lkt0ym/T29V0b0lGr7zelfypcdVR3mKzN8NLmRIDxgyvL11pSTn
            i5tGT/VfcKnb6X4YlLUgSb0nNVkTvP3hWTH3Fy0IADV5gSHtwBCIbpNCFMW1ENDU
            aAEJAhAhdx8wL92m+7Xl00E2xnyDiR7DvqyI3on6igkzjurO3zWY+B9D6gMkxvUL
            ctZRBn7JfNz5T+i6fsg+tZG9+0QQKT4LEiNmEmh5NNpik2RW7F02yoZYz2JGSq+D
            qlGzJXMODPz7
            =qLCA
            -----END PGP MESSAGE-----
          fp: 0231831CB40B8E587B7353CBA3AF727721205A62
    encrypted_regex: ^(ca_password|provisioner_password|intermediate_ca_key|root_ca_key)$
    version: 3.9.4
