apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shlink
  namespace: shlink
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: shlink
      app.kubernetes.io/name: shlink
