apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: semaphore-user-grant
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "ALL PRIVILEGES"
  database: "semaphore"
  table: "*"
  username: "semaphore"
  grantOption: false
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
