apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-store
spec:
  configuration:
    destinationPath: s3://feather-core-cluster-pg-backup/backups-fr01
    endpointURL: http://rook-ceph-rgw-feather-s3.rook-ceph-fr01.svc:80
    s3Credentials:
      accessKeyId:
        name: cnpg-backup
        key: access-key-id
      secretAccessKey:
        name: cnpg-backup
        key: secret-access-key
    wal:
      compression: gzip