apiVersion: v1
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
stringData:
    config.yaml: ENC[AES256_GCM,data:JbGqMifBwLNFixu17fpHxYgw/rSoZJ+yFAtDvOIzrvyU+jgZuD6/K4iOLcTar56fNk+B3sVfo303Z0zu4azREzOQKcZ3P//iiiqlohEdwzoqmhN9kYoFDnIyy6QbRHU7epkIzMM5akJBmt6s1LW5vy0CujKjCkXYJB+CPDQPNO55aatXM2w5ZWxrm7kQKHPsHZ28OcH92yjYFu0aUGoMbgLXjrwHzM4nLIs0tEJ5RYDpOs3+5R/u,iv:8RJY+v4YtAOI+idJDVX8dOgReCWfCMBrPOa5F/fjWZ8=,tag:nxPhulZ4LY1LPuqyLl6rSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-15T18:06:17Z"
    mac: ENC[AES256_GCM,data:Jg3gaRgx2wqn/HkNSzIcg7By262SzoDGhmJ+rTGkwu7egNol0PGQ3Pp8NcVfVxv6AfeLf496Fl4rqO159UuPsV/rfnUIQE5aMx8jwgPPdF7cCEljVtw+1Wamp+UeD8q9vgDhu23ICU5Ou6sw022+jqoLMSUC6xP6WRMZvSC4C+M=,iv:IEmfO/felwi+9kdKeVjdfLLUfdBcqnDs0/Px2aZfOO4=,tag:eU/9dllxzIH/v7Zd7QoXlQ==,type:str]
    pgp:
        - created_at: "2025-03-15T18:06:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwWbRp0WX+I4AQ/+J9eAOA4/rqKA6vXFwnDjNlW+U2MwBQ97aKsMv6kiVqtl
            Iwl4pXbVvjp+fAHIeq7YQ+BWo8gLOyayoCNr57FDklGXQ5P6t5DQLwCT1XuMGPZO
            pb54P9u2q1Mx9GTE3k4gEGUPwVlPm2sLi2YTsMWS05bXqHSbSx1kAmLqxx8vxYgC
            ZXHw46J9hbTzWyrAM+KKjZlt9TI8I6hNNldmZE6iWw64mUsA7PeFBIuIN8SkWA25
            RtGKbixAVRnAOS1RckTihil5T3SaejyzDfUKvmtNWQywUg0aBQZoo88Jk9icgK8y
            DnWtJUyENmnH3shnjRWHNN80gD2y06JLPhTZYncHLVLMRs5U49HIGBBa1W2sNOem
            f1V/B301QycfhQ4yYD/k57wNe8ulV51l9kqpP3Lc8qaN7Iweubzq1X0ultN9N8ad
            zdPMOBABMqfh+8WM99MuwwH3yIC3kKVvmv+1+uMGm6GMLQNghSD4vvVM/uWHagXd
            i6UJWtMulm2iAkUDMmkbHy23fEFm2egoXn2CSXh8gnQ4SKVFPKS9Vv9f6CI469Nr
            IJBH+k2syDl+uTjhVN4ZH3lL3nKebIgo1uIuMrQiq8+extIJvdoG+aqf4DGgGEc1
            CNK9yATehGjU7ppUPEkeUzC/7xeJjOpLXbc37DMMLxPqjPrP901rHQJQ12Ce3kDU
            aAEJAhDjWfif4n8iy5l+8H5oLXnKxTEBsLb2h0lA5kW2d4l0QOjb/9bG6U6Zhds/
            gIHCQJsGqZjkmXi7rWptr2fQUXXn0ZVLrO/Ft/sYzi9yQrxeCQfDGsZOWgQgC+75
            4/9BZVfDsqXy
            =wj1b
            -----END PGP MESSAGE-----
          fp: 0231831CB40B8E587B7353CBA3AF727721205A62
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
