apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: configs
  interval: 10s
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/clusters/feathre-core/base-apps
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      ALLOWED_CIDRS: "172.16.0.0/16,10.200.0.0/16,192.168.0.0/16"
