apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: base-configs
  interval: 10s
  retryInterval: 10s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/clusters/feather-core/controllers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg