apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: s3-migration
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-fr01
  interval: 1h0m0s
  retryInterval: 5m0s
  timeout: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/clusters/feather-core/rook-fr01/migration
  prune: false
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
