apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - otis
  - otis-dev
  - vulpes-backend
  - vulpes-backend-dev
  - stelaris
  - stelaris-dev
  - vulpes-generator
  - vulpes-generator-dev
