apiVersion: v1
kind: Service
metadata:
  name: {{ include "outline.fullname" . }}-collaboration
  labels:
    {{- include "outline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collaboration.service.type }}
  ports:
    - port: {{ .Values.collaboration.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "outline.selectorLabelsCollaboration" . | nindent 4 }}
