{{- $root := . -}}
{{- range $name, $component := .Values.components }}
{{- if $component.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outline.fullname" $root }}-{{ $name }}
  labels:
    {{- include "outline.componentLabels" (dict "root" $root "component" $name) | nindent 4 }}
spec:
  {{- if not (and $component.autoscaling $component.autoscaling.enabled) }}
  replicas: {{ $component.replicaCount }}
  {{- end }}
  {{- with $component.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "outline.componentSelectorLabels" (dict "root" $root "component" $name) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with $root.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "outline.componentLabels" (dict "root" $root "component" $name) | nindent 8 }}
        {{- with $root.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "outline.serviceAccountName" $root }}
      {{- with $root.Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with $root.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $root.Chart.Name }}
          {{- with $root.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          env:
            - name: SERVICES
              value: {{ $component.services | quote }}
            {{- with $root.Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $component.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if $component.http }}
          ports:
            - name: http
              containerPort: {{ $root.Values.service.port }}
              protocol: TCP
          {{- end }}
          {{- with $component.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $component.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $component.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $root.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $root.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ($component.nodeSelector | default $root.Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ($component.affinity | default $root.Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ($component.tolerations | default $root.Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ($component.topologySpreadConstraints | default $root.Values.topologySpreadConstraints) }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
