apiVersion: v1
kind: Service
metadata:
  name: {{ include "outline.fullname" . }}-frontend
  labels:
    {{- include "outline.labelsFrontend" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "outline.selectorLabelsFrontend" . | nindent 4 }}
