apiVersion: v1
kind: Service
metadata:
  name: {{ include "outline.fullname" . }}-frontend
  labels:
    {{- include "outline.labels" . | nindent 4 }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "outline.selectorLabels" . | nindent 4 }}-frontend
