{{- $root := . -}}
{{- range $name, $component := .Values.components }}
{{- if and $component.enabled (default $component.http $component.service) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "outline.fullname" $root }}-{{ $name }}
  labels:
    {{- include "outline.componentLabels" (dict "root" $root "component" $name) | nindent 4 }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "outline.componentSelectorLabels" (dict "root" $root "component" $name) | nindent 4 }}
{{- end }}
{{- end }}
