apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  releaseName: minio-operator
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  values: {}
