apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plane
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/plane/
  - ingress.yaml
patches:
  - path: release.yaml

secretGenerator:
  - name: plane-app-env
    envs:
      - plane.sops.env
  - name: plane-doc-store
    envs:
      - plane.sops.env
  - name: plane-live-env
    envs:
      - plane.sops.env
  - name: plane-rabbitmq
    envs:
      - plane.sops.env
  - name: cf-origin-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=cf-origin-tls.sops.crt
      - tls.key=cf-origin-tls.sops.key
