apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: metabase
spec:
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: user-metabase-secret
    key: password
  # Deckelt den Verbindungsverbrauch des Metabase-Pools.
  maxUserConnections: 10
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
