apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: semaphore
spec:
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: user-semaphore-secret
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
