apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc
spec:
  releaseName: autocert
  chart:
    spec:
      chart: actions-runner-controller
      sourceRef:
        kind: HelmRepository
        name: arc-chart
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
