apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-controller
spec:
  releaseName: actions-runner-controller
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1m0s
  # Default values
  #
  values: {}
