apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - cluster.yaml
  - pooler-rw.yaml
  - pooler-ro.yaml
  - database/harbor.yaml
  - database/outline.yaml
  - database/backstage.yaml

secretGenerator:
  - name: cnpg-backup
    envs:
      - s3-backup.env
  - name: role-outline
    options:
      labels:
        cnpg.io/reload: "true"
    envs:
      - roles/outline.sops.env
  - name: role-harbor
    options:
      labels:
        cnpg.io/reload: "true"
    envs:
      - roles/harbor.sops.env
  - name: role-backstage
    options:
      labels:
        cnpg.io/reload: "true"
    envs:
      - roles/backstage.sops.env