apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - cluster.yaml
  - pooler-rw.yaml
  - pooler-ro.yaml

secretGenerator:
  - name: cnpg-backup
    envs:
      - s3-backup.env