apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  releaseName: loki-stack
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-labs
        namespace: flux-system
  install:
    remediation:
      retries: 1
  interval: 1m0s
  # Default values
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  values: {}
