apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../certificates/clusters/feather-core/cert-manager-issuers
  - ../../../certificates/clusters/feather-core/internal-certs
