apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: outline
spec:
  values:
    image:
      repository: docker.getoutline.com/outlinewiki/outline
      # This sets the pull policy for images.
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "0.87.3"
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 1
        memory: 1Gi
    securityContext:
      readOnlyRootFilesystem: false
      runAsUser: 1000
    volumeMounts:
      - mountPath: /opt/outline/.env
        name: outline-env-file
        readOnly: true
        subPath: .env
    volumes:
      - name: outline-env-file
        secret:
          items:
            - key: .env
              path: .env
          secretName: outline-env

    replicaCount: 1
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/proxy-body-size: "5G"
        nginx.ingress.kubernetes.io/proxy-body-size: "5G"
      hosts:
        - host: outline.onelitefeather.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: outline-onelitefeather-dev-tls
          hosts:
            - outline.onelitefeather.dev
    livenessProbe:
      initialDelaySeconds: 60
      httpGet:
        path: /_health
        port: 3000
    readinessProbe:
      initialDelaySeconds: 60
      httpGet:
        path: /_health
        port: 3000

